Use Auth SDK
saleor/saleor-dashboard pull request #1474
Opened 2021-10-06 11:41 UTC by orzechdev

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-10-06 18:57 UTC, patrys commented
Task linked: [SALEOR-4512 Use Auth SDK in Dashboard](https://app.clickup.com/t/2549495/SALEOR-4512)

2021-11-08 09:15 UTC, Cloud11PL approved these changes

2021-11-10 10:06 UTC, jwm0 requested changes

2021-11-10 10:06 UTC, jwm0 commented on src/components/AppLayout/AppChannelContext.tsx
> +    skip: !authenticated || authenticating
```suggestion
    skip: !authenticated
```
We only care if the user is `authenticated`, why do we need to check if it's in flight as well?

2021-11-10 10:06 UTC, jwm0 commented on src/components/Shop/index.tsx
> +    <TypedShopInfoQuery skip={!authenticated || authenticating}>
Same here

2021-11-10 10:06 UTC, jwm0 commented on src/index.tsx
> +  autologin: true
autologin is `true` by default

2021-11-10 10:06 UTC, jwm0 commented on src/index.tsx
> +  const homePageLoaded = channelLoaded && authenticated && !authenticating;
`authenticated` and `authenticating` are mutually exclusive. They can never both be `true`, so you might just want to skip the last check.

2021-11-10 10:06 UTC, jwm0 commented on src/auth/hooks/useAuthProvider.ts
> +  const autologinPromise = useRef<Promise<any>>();
Why are we passing a promise to context? If it's inside context it's only consumed by other react components, so why not use a state to check for resolve status?

2021-11-10 10:33 UTC, orzechdev commented on src/auth/views/Login.tsx
> +  ] = useLocalStorage("requestedExternalPluginId", null);
SDK keeps information of pluginID which was used to log in, while here we are keeping pluginID which was used for redirection to external OAuth, thus we cannot use state as it won't be preserved after rdirection.

2021-11-10 15:11 UTC, orzechdev commented on src/auth/utils.ts
> +    notify({
Ok, I've changed it to separate messages `sessionExpired` and `somethingWentWrong` respectively

2021-11-10 15:14 UTC, orzechdev commented on src/auth/hooks/useAuthProvider.ts
> +      logout();
Removed

2021-11-12 13:11 UTC, orzechdev commented on src/auth/types.ts
> +} from "@saleor/sdk/dist/apollo/types";
Updated, please check out

2021-11-15 09:36 UTC, jwm0 approved these changes

2021-11-15 09:36 UTC, jwm0 commented on src/components/AppLayout/AppChannelContext.tsx
> +    onChannelChange(selectedChannel);
This method should ideally be accessible from a SDK hook. Something along the lines of:
```
const { channel, setChannel } = useSaleorConfig();
```

2021-11-15 11:36 UTC, jwm0 approved these changes

2021-12-07 11:04 UTC, eCzerniak approved these changes

2021-12-17 11:10 UTC, merged