Disable save in product create & edit when product name is empty
saleor/saleor-dashboard pull request #1551
Opened 2021-10-27 11:34 UTC by Droniu

I want to merge this change because... it disables save button in product create & edit forms when product name is not provided.

Also disables form when SKU is empty in both product & variant edit pages.

**PR intended to be tested with API branch:**  3.0

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://stable.staging.saleor.cloud/graphql/

2021-11-02 07:57 UTC, bmigirl requested changes

2021-11-02 07:57 UTC, bmigirl commented on src/products/components/ProductCreatePage/form.tsx
>    const disabled =
Lets make a function of it, it was hardly readable before and it's only more so now

2021-11-02 07:57 UTC, bmigirl commented on src/products/components/ProductUpdatePage/form.tsx
> +    (!opts.hasVariants &&
Also function plz

2021-11-03 08:01 UTC, bmigirl requested changes

2021-11-03 08:01 UTC, bmigirl commented on src/products/components/ProductCreatePage/form.tsx
> +  const disabled = shouldEnableSave();
```suggestion
  const disabled = !shouldEnableSave();
```

2021-11-03 08:01 UTC, bmigirl commented on src/products/components/ProductUpdatePage/form.tsx
> +  const disabled = shouldEnableSave();
```suggestion
  const disabled = !shouldEnableSave();
```

2021-11-04 09:20 UTC, bmigirl approved these changes

2021-11-30 09:02 UTC, bmigirl approved these changes

2021-11-30 09:12 UTC, orzechdev approved these changes

2021-12-22 07:42 UTC, merged