Allow returning & refunding partially paid orders
saleor/saleor-dashboard pull request #1572
Opened 2021-11-05 14:49 UTC by Droniu

I want to merge this change because it allows returning, replacing and refunding products in partially paid orders.

**PR intended to be tested with API branch:**  3.0

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://stable.staging.saleor.cloud/graphql/

2021-11-05 14:49 UTC, patrys commented
Task linked: [SALEOR-4839 Automatic return/refund does't work on partially paid orders](https://app.clickup.com/t/2549495/SALEOR-4839)

2021-11-05 15:10 UTC, Cloud11PL requested changes

2021-11-05 15:10 UTC, Cloud11PL commented on src/orders/components/OrderRefundReturnAmount/OrderRefundReturnAmount.tsx
> +  const shouldDisableRefundButton = () => {
```suggestion
  const shouldRefundButtonBeDisabled = () => {
```
I think it's a bit clearer

2021-11-08 08:33 UTC, dominik-zeglen approved these changes

2021-11-08 09:14 UTC, Cloud11PL approved these changes

2021-11-18 11:40 UTC, jwm0 approved these changes

2021-11-18 11:42 UTC, merged