Add sorting products by update at date
saleor/saleor-dashboard pull request #1581
Opened 2021-11-08 18:52 UTC by orzechdev

I want to merge this change because... it adds option to sort products by update date.

**PR intended to be tested with API branch:**  main

### Screenshots

<img width="1245" alt="Zrzut ekranu 2021-11-8 o 19 21 31" src="https://user-images.githubusercontent.com/9825562/140800400-a63c7c41-e4b5-45ef-aaa7-9fa2461a1f46.png">

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-11-08 18:52 UTC, patrys commented
Task linked: [SALEOR-4838 Add created/updated sortable column to product list view](https://app.clickup.com/t/2549495/SALEOR-4838)

2021-11-09 08:53 UTC, Droniu approved these changes

2021-11-10 12:21 UTC, dominik-zeglen approved these changes

2021-11-10 12:22 UTC, jwm0 approved these changes

2021-11-10 12:31 UTC, jwm0 requested changes
We intentionally had "Price" set always at the last column, as it aligns the text to the right. From my perspective this column ("Last updated") should come before "Price" so we preserve the old behaviour. Please confirm this with @pwgryglak

2021-11-15 11:32 UTC, jwm0 approved these changes

2021-11-16 15:39 UTC, orzechdev commented
@Droniu Please also confirm if manual tests work for you (due to temporary lack of QA)

2021-11-17 10:15 UTC, Droniu approved these changes

2021-11-17 12:47 UTC, Droniu approved these changes

2021-11-17 12:49 UTC, merged