Random fixes part 3
saleor/saleor-dashboard pull request #1647
Opened 2021-12-02 13:47 UTC by dominik-zeglen

I want to merge this change because it's another batch of random fixes after bumping to macaw 0.3.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-12-02 16:04 UTC, jwm0 approved these changes

2021-12-06 09:20 UTC, bmigirl requested changes

2021-12-06 09:20 UTC, bmigirl commented on src/channels/components/ShippingZonesCard/ShippingZonesCardListFooter.tsx
> +const useStyles = makeStyles(
Local styles file

2021-12-06 09:20 UTC, bmigirl commented on src/components/ChannelsAvailabilityCard/ChannelsAvailabilityCard.stories.tsx
> +        setAvailabilityDateLabel: "xd4"
Are all those messages correct?

2021-12-06 10:44 UTC, bmigirl approved these changes

2021-12-06 11:11 UTC, merged