Add tests for updating & deleting collections and categories
saleor/saleor-dashboard pull request #1662
Opened 2021-12-05 15:12 UTC by karola312

I want to merge this change because I created tests for updating/deleting categories and collections 

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-12-05 15:12 UTC, patrys commented
Task linked: [SALEOR-5005 Add test for updating and deleting categories & collections](https://app.clickup.com/t/2549495/SALEOR-5005)

2021-12-14 08:53 UTC, eCzerniak commented on cypress/integration/catalog/categories.js
> +      const categoryName = `${startsWith}${faker.datatype.number()}`;
Add an empty space.

2021-12-14 08:53 UTC, eCzerniak commented on cypress/integration/catalog/categories.js
> +      const updatedName = `${startsWith}updatedCategory`;
Add an empty space.

2021-12-14 08:53 UTC, eCzerniak commented on cypress/integration/catalog/collections.js
> +      const collectionName = `${startsWith}${faker.datatype.number()}`;
Add an empty space.

2021-12-14 08:54 UTC, eCzerniak commented on cypress/integration/catalog/collections.js
> +      const updatedName = `${startsWith}updatedCollection`;
Add an empty space.

2021-12-14 09:43 UTC, eCzerniak requested changes
![image](https://user-images.githubusercontent.com/29308910/145973391-241d58df-210f-46d5-902d-a04c0617f21e.png)
![image](https://user-images.githubusercontent.com/29308910/145973414-914e3161-4117-435c-825b-6c6eb8550a0c.png)

Create category and add subcategory are failing.

2021-12-15 10:01 UTC, Cloud11PL approved these changes

2021-12-17 07:30 UTC, eCzerniak approved these changes

2021-12-17 10:36 UTC, merged