Fix failing cypress tests
saleor/saleor-dashboard pull request #1671
Opened 2021-12-08 10:29 UTC by karola312

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-12-08 10:29 UTC, patrys commented
Task linked: [SALEOR-5070 Fix failing tests](https://app.clickup.com/t/2549495/SALEOR-5070)

2021-12-13 11:06 UTC, eCzerniak requested changes
![image](https://user-images.githubusercontent.com/29308910/145795439-b1bcfe37-aa49-4316-9b0d-c7d24178185b.png)
This error is shown in preorders tests (all). 
Also what do you think about changing the description in those tests, because now  both starts from `Creating variants ` 
![image](https://user-images.githubusercontent.com/29308910/145796471-44b4df1f-4731-4695-9eae-feb760655cf7.png)

Also, here when we get all images at productList view we are counting also image from avatar which cause the error message.
![image](https://user-images.githubusercontent.com/29308910/145798895-6106932b-4da9-44a4-9046-20d24600d4d6.png)


![image](https://user-images.githubusercontent.com/29308910/145798210-00b0075b-ae0d-45e6-aca9-12afd2865bc2.png)

2021-12-15 12:10 UTC, karola312 commented
I fixed preorders & images

2021-12-15 12:40 UTC, dominik-zeglen approved these changes

2021-12-17 07:34 UTC, eCzerniak approved these changes

2021-12-17 11:07 UTC, merged