Fix rest of the world checkbox on shipping zone create
saleor/saleor-dashboard pull request #1672
Opened 2021-12-08 12:15 UTC by orzechdev

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-12-08 12:15 UTC, patrys commented
Task linked: [SALEOR-4936 Shipping Zone - Assign countries - Rest of the World checkbox is not working.](https://app.clickup.com/t/2549495/SALEOR-4936)

2022-02-03 08:31 UTC, Cloud11PL requested changes

2022-02-03 08:31 UTC, Cloud11PL commented on src/shipping/components/ShippingZoneCountriesAssignDialog/ShippingZoneCountriesAssignDialog.tsx
> +          const restOfTheWorld = isRestWorldCountriesSelected(
```suggestion
          const isRestOfTheWorldSelected = isRestWorldCountriesSelected(
```

2022-02-03 11:30 UTC, Cloud11PL approved these changes

2022-02-03 13:38 UTC, bmigirl approved these changes

2022-02-07 09:52 UTC, eCzerniak requested changes
If all countries are assigned then "Rest of the world" section should be hidden.

2022-02-09 09:47 UTC, merged