Add tests for delete/update warehouse
saleor/saleor-dashboard pull request #1676
Opened 2021-12-10 12:30 UTC by karola312

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-12-10 12:30 UTC, patrys commented
Task linked: [SALEOR-5020 Add tests for warehouses](https://app.clickup.com/t/2549495/SALEOR-5020)

2021-12-13 10:04 UTC, bmigirl approved these changes

2021-12-15 11:02 UTC, eCzerniak requested changes
1. This PR is going to be merged to 3.0 but pinned backend is master (which is 3.1) I wonder if those tests were checked with proper backend? 
2.  I have some problems with `should add warehouse to shipping zone`
![image](https://user-images.githubusercontent.com/29308910/146174861-b06e8991-ebb8-48b2-9270-9fbc12c9be16.png)
3. .. and with `should remove warehouse from shipping zone `
![image](https://user-images.githubusercontent.com/29308910/146174975-63d708de-096d-47f0-811e-69b22cdb22a4.png)

2021-12-15 11:54 UTC, eCzerniak approved these changes

2021-12-15 11:56 UTC, merged