Add tests for updating/deleting shipping
saleor/saleor-dashboard pull request #1691
Opened 2021-12-16 11:41 UTC by karola312

I want to merge this change because I want to add tests for updating and deleting shipping methods and zones

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://stable.staging.saleor.cloud/graphql/

2021-12-16 11:41 UTC, patrys commented
Task linked: [SALEOR-5019 Add tests for shipping Method](https://app.clickup.com/t/2549495/SALEOR-5019)

2021-12-17 09:07 UTC, Cloud11PL approved these changes

2021-12-17 09:07 UTC, Cloud11PL commented on cypress/fixtures/urlList.js
> +  priceRete: "price/",
Rete?

2021-12-17 11:22 UTC, karola312 commented on cypress/fixtures/urlList.js
> +  priceRete: "price/",
PriceRate, I fixed it

2021-12-21 07:39 UTC, eCzerniak requested changes

2021-12-30 12:44 UTC, eCzerniak approved these changes
Please change this one line and it will be OK.

2021-12-30 12:44 UTC, eCzerniak commented on cypress/fixtures/urlList.js
> +  `${urlList.shippingMethods}${shippingZoneId}/${urlList.priceRete}${priceRateId}`;
```suggestion
  `${urlList.shippingMethods}${shippingZoneId}/${urlList.priceRate}${priceRateId}`;
```

2022-01-03 12:47 UTC, merged