Refactor changing address in order details directly
saleor/saleor-dashboard pull request #1697
Opened 2021-12-17 12:06 UTC by Droniu

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-12-17 12:06 UTC, patrys commented
Task linked: [SALEOR-4959 Refactor changing address in order details directly](https://app.clickup.com/t/2549495/SALEOR-4959)

2022-01-03 10:48 UTC, dominik-zeglen requested changes
See also:
https://github.com/erlang/otp/wiki/writing-good-commit-messages

2022-01-03 10:48 UTC, dominik-zeglen commented on src/storybook/config.js
> +  require("./stories/orders/OrderCustomerAddressesEditDialog");
It's a legacy code, if you name file `*.stories.tsx` it'll be autodiscovered by storybook and will not be needed here

2022-01-03 10:48 UTC, dominik-zeglen commented on src/storybook/stories/orders/OrderCustomerAddressesEditDialog.tsx
> +  AddressEditDialogVariant,
You can just put this file in the same directory as component

2022-01-03 10:48 UTC, dominik-zeglen commented on src/storybook/stories/orders/OrderCustomerAddressesEditDialog.tsx
>  storiesOf("Orders / OrderCustomerAddressesEditDialog", module)
We can name it in some meaningful way, like "Change order customer" or whatever this component does

2022-01-03 10:48 UTC, dominik-zeglen commented on src/orders/views/OrderDetails/OrderAddressFields.tsx
> +import { CustomerAddresses_user } from "@saleor/customers/types/CustomerAddresses";
Regarding component placement, it's not actually a view component

2022-01-03 11:50 UTC, Droniu commented on src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesEditDialog.tsx
> +  ) => ({
My idea was to extract these props so that render logic is more readable. I'll move it outside this file because it's already pretty big.

2022-01-03 12:16 UTC, dominik-zeglen commented on src/orders/views/OrderDetails/OrderUnconfirmedDetails/index.tsx
> +  orderUpdate: any;
That's not going to happen

2022-01-04 10:29 UTC, bmigirl requested changes

2022-01-04 10:29 UTC, bmigirl commented on src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesEditDialog.tsx
> +    !hasCustomerChanged &&
Would rather see it if'ed so it's easier to read

2022-01-14 08:01 UTC, pwgryglak approved these changes

2022-01-14 08:15 UTC, pwgryglak requested changes
Couple of issues listed below

- Hover effect on modals is cut see screen: 
![Screenshot 2022-01-14 at 09 05 14](https://user-images.githubusercontent.com/40759237/149472790-b7e4967b-31fc-439c-8274-9366522e8519.png)

- if user has no defined addresses system shows this instead of a standard form
![Screenshot 2022-01-14 at 09 05 56](https://user-images.githubusercontent.com/40759237/149472909-35b7415d-62d9-437c-80d8-2b73e105983b.png)
Issue here is that there are no addresses to be found + hitting select gives user "Saleor ran into an unexpected problem" prompt. We should use standard form in this case instead. 

Next issue is:
- Orders where customers doesn't have saved addresses, and order has address, we shouldn't render "This customer doesn't have any shipping addresses. Provide address for order". Also the form is not filled with provided address so there's no ability to just edit one field - you have to provide it from scratch

We should render only: "Provide address for order" and fill the inputs with address
![Screenshot 2022-01-14 at 09 14 55](https://user-images.githubusercontent.com/40759237/149474111-3dec0bd9-d9b9-4964-afc2-e8c4501375fd.png)

2022-01-14 09:45 UTC, bmigirl requested changes

2022-01-14 09:45 UTC, bmigirl commented on src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressEdit.tsx
> +    hideCard = false
Not a big fan of negative based props like this, I think it's always less complicated to think in positives, especially when adding negations later. Right now I can see it's used like so:
```hideCard: !hasCustomerChanged``` and ```!hideCard``` -> using it with negations every everywhere
We could change it to `showCard` and then do
```showCard: hasCustomerChanged``` and ```showCard```

2022-01-14 09:45 UTC, bmigirl commented on src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesEditDialog.tsx
>  export interface OrderCustomerSearchAddressState {
Can we add local types file for these?

2022-01-14 09:45 UTC, bmigirl commented on src/orders/views/OrderDetails/OrderDraftDetails/index.tsx
> +export const isAnyAddressEditModalOpen = (uri: string | undefined): boolean =>
```["edit-customer-addresses", "edit-shipping-address", "edit-billing-address"].includes(uri)``` ?

2022-01-20 09:15 UTC, bmigirl approved these changes

2022-01-24 09:52 UTC, dominik-zeglen requested changes

2022-01-24 09:52 UTC, dominik-zeglen commented on src/customers/components/CustomerAddressChoiceCard/styles.ts
> +      borderColor: theme.palette.grey[200],
```suggestion
      borderColor: theme.palette.divider,
```

or `theme.palette.saleor.main[4]` or whatever the color number is in figma

2022-01-24 09:52 UTC, dominik-zeglen commented on src/components/CardSpacer.tsx
> +      marginTop: theme.spacing(2)
I'm not convinced that it's intentional change

2022-01-24 09:52 UTC, dominik-zeglen commented on src/orders/components/OrderAddressFields/OrderAddressFields.tsx
> +  const addressFieldCommonProps = {
A nitpick really, but it could be types as `Partial<OrderCustomerAddressesEditDialogProps>`

2022-01-24 09:52 UTC, dominik-zeglen commented on src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesEditDialog.stories.tsx
> +storiesOf("Orders / Changing address in order", module)
Oh yes yes bull +1 *drinks monster energy drink*

2022-01-24 09:52 UTC, dominik-zeglen commented on src/orders/components/OrderCustomerAddressesEditDialog/OrderCustomerAddressesEditDialog.stories.tsx
> +  .add("Address change when customer is changed", () => (
Another nitpick but every other story at this level is written in lowercase 🤷‍♂️

2022-01-24 09:52 UTC, dominik-zeglen commented on src/orders/components/OrderCustomerAddressesEditDialog/utils.ts
> +  countryChoices: Array<{ label: string; value: string }>;
```suggestion
  countryChoices: Choice[];
```

Or something like this, it's located somewhere near `SingleAutocompleteSelectField`

2022-01-24 09:52 UTC, dominik-zeglen commented on src/orders/components/OrderCustomerAddressesEditDialog/utils.ts
> +  ) => void,
If we're using react types, let's be consistent 

```suggestion
  setAddressSearchState: React.Dispatch<React.SetStateAction<OrderCustomerSearchAddressState>>;
```

2022-01-24 09:52 UTC, dominik-zeglen commented on src/orders/views/OrderDetails/OrderDraftDetails/index.tsx
> +    if (orderDraftUpdate?.opts?.data?.draftOrderUpdate?.errors?.length) {
I'm not sure if `orderDraftUpdate` would update after calling `mutate`. Can you confirm it actually happens?

2022-01-24 09:52 UTC, dominik-zeglen commented on src/orders/views/OrderDetails/OrderNormalDetails/index.tsx
> +  };
This async function's return type is marked as `Promise`, but it doesn't await nor return anything, so I guess it can be regular void function

2022-01-24 09:52 UTC, dominik-zeglen commented on src/orders/views/OrderDetails/OrderUnconfirmedDetails/index.tsx
> +  };
It's not a very good pattern. Here you just await promise, just to wrap it into another promise. Effectively comes to this:

```suggestion
  const handleCustomerChangeAddresses = (
    data: Partial<OrderCustomerAddressesEditDialogOutput>
  ): Promise<any> => orderUpdate.mutate({
      id,
      input: data
    });
```

2022-01-27 08:33 UTC, dominik-zeglen approved these changes

2022-01-31 13:45 UTC, dominik-zeglen approved these changes

2022-01-31 13:46 UTC, bmigirl approved these changes

2022-01-31 14:02 UTC, eCzerniak approved these changes

2022-01-31 14:11 UTC, merged