Site settings typos fixes
saleor/saleor-dashboard pull request #1716
Opened 2021-12-23 11:28 UTC by Cloud11PL

I want to merge this change because it fixes typos in site settings.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-12-23 11:28 UTC, patrys commented
Task linked: [SALEOR-4735 [Site Settings] [Content] Typo and lack of spaces in Company Information.](https://app.clickup.com/t/2549495/SALEOR-4735)

2021-12-23 12:00 UTC, jwm0 approved these changes
Update snapshots

2021-12-27 09:05 UTC, dominik-zeglen approved these changes

2021-12-30 13:07 UTC, eCzerniak requested changes

2021-12-30 13:07 UTC, eCzerniak commented on src/siteSettings/components/SiteSettingsPage/SiteSettingsPage.tsx
> +                    defaultMessage="This address will be used to generate invoices and calculate shipping rates. Email address you provide here will be used as a contact adress for your customers."
```suggestion
                    defaultMessage="This address will be used to generate invoices and calculate shipping rates. Email address you provide here will be used as a contact address for your customers."
```

2022-01-11 08:00 UTC, eCzerniak approved these changes

2022-01-11 12:37 UTC, merged