Shipping zones button fix
saleor/saleor-dashboard pull request #1717
Opened 2021-12-23 12:00 UTC by Cloud11PL

I want to merge this change because it shows the user more clearly how many zones has been selected. The submitted "bug" isn't a bug - it's just a confusion caused by a button not appearing when all zones are selected. 

**PR intended to be tested with API branch:** 

### Screenshots

Before:
![image](https://user-images.githubusercontent.com/13994677/147237390-c73586d1-96e5-4117-ab2c-b6f1b31db600.png)

After:
![image](https://user-images.githubusercontent.com/13994677/147237446-523aad79-e695-4a2b-bade-65d7ff481875.png)
![image](https://user-images.githubusercontent.com/13994677/147237486-838abab5-393d-4832-ab3e-5b8029fbbe76.png)

### Pull Request Checklist

1. [x] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://stable.staging.saleor.cloud/graphql/

2021-12-23 12:00 UTC, patrys commented
Task linked: [SALEOR-4603 Add shipping zones button dissapear](https://app.clickup.com/t/2549495/SALEOR-4603)

2021-12-23 14:56 UTC, orzechdev approved these changes

2021-12-27 04:57 UTC, Droniu approved these changes

2022-01-10 14:25 UTC, pwgryglak approved these changes

2022-01-24 09:35 UTC, dominik-zeglen requested changes

2022-01-24 09:35 UTC, dominik-zeglen commented on src/storybook/__snapshots__/Stories.test.ts.snap
> +              0 /  Shipping Zones
I think you forgot to update story

2022-01-27 08:24 UTC, Droniu commented on src/channels/components/ShippingZonesCard/ShippingZonesCard.tsx
> +      "Select shipping zones that will be supplied via this channel. You can assign Shipping Zones to multiple channels.",
```suggestion
      "Select shipping zones that will be supplied via this channel. You can assign shipping zones to multiple channels.",
```

2022-01-27 09:40 UTC, Cloud11PL commented on src/channels/components/ShippingZonesCard/ShippingZonesCard.tsx
> +      "Select shipping zones that will be supplied via this channel. You can assign Shipping Zones to multiple channels.",
Fixed

2022-02-01 09:30 UTC, dominik-zeglen approved these changes

2022-02-01 11:40 UTC, merged