Redirect user to creater variant after variant create
saleor/saleor-dashboard pull request #1771
Opened 2022-01-19 12:47 UTC by Cloud11PL

I want to merge this change because it redirects user to the created variant after variant creation. 

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://stable.staging.saleor.cloud/graphql/

2022-01-19 12:47 UTC, patrys commented
Task linked: [SALEOR-3765 Variants edition - Create Variant is shown after the successful creation of a variant.](https://app.clickup.com/t/2549495/SALEOR-3765)

2022-01-20 08:38 UTC, dominik-zeglen requested changes
You can just use `onCompleted` argument in mutation hook

2022-01-20 09:16 UTC, bmigirl approved these changes

2022-01-21 09:27 UTC, dominik-zeglen approved these changes

2022-01-24 11:20 UTC, eCzerniak approved these changes

2022-01-25 09:39 UTC, merged