Add new tests for product types
saleor/saleor-dashboard pull request #1775
Opened 2022-01-20 12:21 UTC by karola312

I want to merge this change because I added tests for product types

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2022-01-20 12:21 UTC, patrys commented
Task linked: [SALEOR-5678 Delete product type and remove attribute](https://app.clickup.com/t/2549495/SALEOR-5678)

2022-01-21 08:45 UTC, Cloud11PL requested changes

2022-01-21 08:45 UTC, Cloud11PL commented on cypress/support/api/requests/Product.js
> +  }]`
I think formatting is a bit off

2022-01-21 08:45 UTC, Cloud11PL commented on cypress/support/api/requests/ProductType.js
> +    productAttributeAssign(productTypeId:"${productTypeId}" operations:{
```suggestion
    productAttributeAssign(productTypeId:"${productTypeId}", operations:{
```
It was okay without the comma? Alternatively the formatting is off

2022-01-24 09:07 UTC, Cloud11PL approved these changes

2022-01-24 12:51 UTC, eCzerniak requested changes
Please change the naming of test cases as it should be. 
e.g As an admin I should be able to create product type without shipping required

2022-01-24 12:51 UTC, eCzerniak commented on cypress/integration/configuration/productTypes.js
>    describe("Tests for product types", () => {
```suggestion
  describe("As an admin I want to manage product types", () => {
```

2022-01-26 10:29 UTC, eCzerniak approved these changes

2022-01-27 10:27 UTC, merged