Add test for creating product type with gift card kind
saleor/saleor-dashboard pull request #1776
Opened 2022-01-20 13:05 UTC by karola312

I want to merge this change because I added test for creating product type with gift card kind

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2022-01-20 13:05 UTC, patrys commented
Task linked: [SALEOR-5677 As an admin I should be able to create product type with gift card kind](https://app.clickup.com/t/2549495/SALEOR-5677)

2022-01-20 14:08 UTC, orzechdev approved these changes

2022-01-21 09:07 UTC, eCzerniak requested changes
As we decided to stick to naming with user stories can we start to changing the naming as it is wrote in our file with test cases?

2022-01-24 12:39 UTC, eCzerniak requested changes
`describe("Tests for product types", () => {`
 change to: 
 `describe("As an admin I want to manage product types", () => {`

2022-01-26 10:31 UTC, eCzerniak approved these changes

2022-01-31 09:25 UTC, merged