Update for translation page test: added test case for modification of…
saleor/saleor-dashboard pull request #1778
Opened 2022-01-20 14:02 UTC by Kjaroszew

… existing translation.

I want to merge this change because new tescase added for translations test.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://stable.staging.saleor.cloud/graphql/

2022-01-20 14:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/saleor/saleor-dashboard?pullRequest=1778) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/saleor/saleor-dashboard?pullRequest=1778) before we can accept your contribution.<br/><hr/>**Klaudia Jaroszewicz** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/saleor/saleor-dashboard?pullRequest=1778) it.</sub>

2022-01-20 14:32 UTC, eCzerniak requested changes
Could we move `translation.js` out of configuration and as we can see at the image we decided to use stories so could we start with changing the naming of test scenario? 
![image](https://user-images.githubusercontent.com/29308910/150358051-5d49edc0-aae4-4450-ae29-bf85653a198f.png)

2022-01-21 09:41 UTC, karola312 requested changes

2022-01-21 09:41 UTC, karola312 commented on cypress/support/pages/translationsPage.js
> +    // skeleton -> loading elements
Remove comment

2022-01-24 13:17 UTC, eCzerniak approved these changes
As we talked please change location of translations tests and it is ready to merge.

2022-01-24 13:49 UTC, karola312 approved these changes

2022-01-24 13:54 UTC, merged