Add tests for gift cards
saleor/saleor-dashboard pull request #1779
Opened 2022-01-21 13:52 UTC by karola312

I want to merge this change because I added tests for activate/disable multiple gift cards, purchase gift card as product and I updated existing tests for gift cards

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

2022-01-21 13:52 UTC, patrys commented
Task linked: [SALEOR-5475 Update tests for gift cards](https://app.clickup.com/t/2549495/SALEOR-5475)

2022-01-24 12:32 UTC, eCzerniak requested changes
Also, tests for `createGiftCards.js` are not working because correct selector is
`[data-test-id="issue-card-button"]` 
but we are using an old one:
`[data-test-id="issueCardButton"]`

2022-01-24 12:32 UTC, eCzerniak commented on cypress/integration/catalog/giftCards/purchaseGiftCard.js
> +  describe("Gift cards in checkout", () => {
```suggestion
  describe("As a customer I should be able to purchase gift card as a product", () => {
```

2022-01-24 12:32 UTC, eCzerniak commented on cypress/integration/catalog/giftCards/updatingGiftCards.js
> +  describe("Tests for gift cards", () => {
```suggestion
  describe("As an admin I want to update gift card", () => {
```

2022-01-24 12:32 UTC, eCzerniak commented on cypress/elements/giftCard/giftCardList.js
> -  issueCardButton: '[data-test-id="issueCardButton"]'
Can we move this file to `cypress/elements/catalog/giftCards/giftCardList.js`  or smg like this?

2022-01-25 09:57 UTC, bmigirl approved these changes

2022-01-28 07:21 UTC, eCzerniak requested changes

2022-01-28 07:21 UTC, eCzerniak commented on cypress/elements/giftCard/giftCardList.js
> -  issueCardButton: '[data-test-id="issueCardButton"]'
@karola312 giftCards are in the catalog section I mean that maybe we should create folder in the catalog and put there files with giftCardList.js. 
` cypress/elements/giftCards/giftCardList.js`  ->  `cypress/elements/catalog/giftCards/giftCardList.js `

2022-02-01 09:09 UTC, eCzerniak approved these changes

2022-02-01 09:09 UTC, eCzerniak commented on cypress/integration/catalog/giftCards/activateGiftCards.js
> +    it("should not be able to disable gift card and use it in checkout. TC: SALEOR_1006", () => {
```suggestion
    it("should not be able to disable gift card and use it in checkout. TC: SALEOR_1007", () => {
```

2022-02-01 10:58 UTC, merged