Add tests for categories
saleor/saleor-dashboard pull request #1786
Opened 2022-01-24 11:19 UTC by karola312

I want to merge this change because I added test for removing subcategory from main category and for deleting categories in categories list

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://stable.staging.saleor.cloud/graphql/

2022-01-24 11:19 UTC, patrys commented
Task linked: [SALEOR-5584 Create missing tests for categories](https://app.clickup.com/t/2549495/SALEOR-5584)

2022-01-24 13:18 UTC, eCzerniak requested changes

2022-01-27 08:14 UTC, jwm0 commented on cypress/integration/catalog/categories.js
> +    it("As an admin I should be able to create category", () => {
the `it` is supposed to be treated like a prefix to the sentence, for example:
```
it("creates a new category")
it("creates category as subcategory")
it("adds product to category")
it("removes category")
...
)
```
cc @eCzerniak

2022-01-28 07:24 UTC, eCzerniak approved these changes
Please change `it` sentence and it it OK.

2022-02-01 11:02 UTC, merged