fix failing tests
saleor/saleor-dashboard pull request #1797
Opened 2022-01-26 08:02 UTC by karola312

I want to merge this change because I fixed failing tests for 3.1

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2022-01-26 08:03 UTC, patrys commented
Task linked: [SALEOR-5606 Fix failing tests](https://app.clickup.com/t/2549495/SALEOR-5606)

2022-01-28 08:24 UTC, eCzerniak requested changes
Can you check the results of e2e tests? As I can see several tests failed, when you will check it and it will be OK then please merge if not add me once more to review.

2022-01-28 09:57 UTC, karola312 commented
@eCzerniak I fixed translations and navigation, test for creating product without SKU I will fix in next PR, tests for variantSelection, siteSettings, images should be failing due to existing bugs. Tests for stripe and adyen are passing with right    keys on qa

2022-01-28 10:54 UTC, bmigirl approved these changes

2022-01-28 13:06 UTC, eCzerniak approved these changes

2022-01-31 08:37 UTC, merged