Saleor 5500 test update translation
saleor/saleor-dashboard pull request #1798
Opened 2022-01-26 09:41 UTC by Kjaroszew

I want to merge this change because moving translations file position to correct folder.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://stable.staging.saleor.cloud/graphql/

2022-01-26 09:41 UTC, patrys commented
Task linked: [SALEOR-5500 Update tests for translations](https://app.clickup.com/t/2549495/SALEOR-5500)

2022-01-26 09:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/saleor/saleor-dashboard?pullRequest=1798) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/saleor/saleor-dashboard?pullRequest=1798) before we can accept your contribution.<br/><hr/>**Klaudia Jaroszewicz** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/saleor/saleor-dashboard?pullRequest=1798) it.</sub>

2022-01-31 11:35 UTC, eCzerniak requested changes

2022-01-31 11:35 UTC, eCzerniak commented on cypress/integration/translations.js
> +    it("As an admin I want to create translation", () => {
and add number of TC

2022-02-03 07:28 UTC, eCzerniak requested changes
@Kjaroszew  Why we have two files with the same cases? One of it should be removed and in the file which should stay `cypress/integration/translations.js ` naming of test cases should be changed.

2022-02-08 09:27 UTC, closed without merging