Add tests for product types for 3.1
saleor/saleor-dashboard pull request #1806
Opened 2022-01-27 11:00 UTC by karola312

I want to merge this change because I added tests for product types for 3.1

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

2022-01-27 11:00 UTC, patrys commented
Task linked: [SALEOR-5678 Delete product type and remove attribute](https://app.clickup.com/t/2549495/SALEOR-5678)

2022-01-27 11:30 UTC, Cloud11PL approved these changes

2022-01-31 11:00 UTC, eCzerniak requested changes

2022-02-01 09:23 UTC, eCzerniak requested changes
Please add SALEOR_1508 case because it is missing.

2022-02-02 14:03 UTC, eCzerniak requested changes
Also don't you think that it is not too much of TCs in one file?

2022-02-02 14:03 UTC, eCzerniak commented on cypress/integration/configuration/productTypes.js
> +    it("should be able to remove variant attribute from product type. TC: SALEOR_1506", () => {
This case or 1507 sometime is failing.
![image](https://user-images.githubusercontent.com/29308910/152168569-47672286-1b03-4e70-9b75-bf85ce06830f.png)

2022-02-03 07:46 UTC, eCzerniak commented
> Also don't you think that it is not too much of TCs in one file?

@karola312 what about that comment? I do not see any answer.

2022-02-03 13:05 UTC, karola312 commented
You're right, I will split this file, and fix 1507

2022-02-07 08:38 UTC, eCzerniak approved these changes
Please change this one name of TC and it is ready to merge.

2022-02-07 08:38 UTC, eCzerniak commented on cypress/integration/configuration/productTypes/attributesInProduductTypes.js
> +    it("As an admin I should be able to select attribute as variant selection. TC: SALEOR_1508", () => {
```suggestion
    it("should be able to select attribute as variant selection. TC: SALEOR_1508", () => {
```

2022-02-07 08:40 UTC, eCzerniak approved these changes

2022-02-07 08:41 UTC, eCzerniak approved these changes

2022-02-07 09:30 UTC, merged