Update data test ids for 3.1
saleor/saleor-dashboard pull request #1814
Opened 2022-01-31 10:49 UTC by karola312

I want to merge this change because I updated data test ids for 3.1

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

2022-01-31 10:49 UTC, patrys commented
Task linked: [SALEOR-5141 Update test attributes names](https://app.clickup.com/t/2549495/SALEOR-5141)

2022-02-02 16:17 UTC, orzechdev approved these changes

2022-02-07 11:28 UTC, eCzerniak requested changes
Please check your PR because some tests are failing and this is connected with some fronted problems. Tests look ok.

2022-02-08 11:41 UTC, karola312 commented on cypress/integration/products/productsList/pagination.js
> +        // cy.get(PRODUCTS_LIST.productsList)
I removed comment

2022-02-08 13:04 UTC, eCzerniak approved these changes

2022-02-11 10:27 UTC, eCzerniak commented
Could you please change API_URI to master staging?

2022-02-11 10:44 UTC, eCzerniak approved these changes

2022-02-11 11:28 UTC, merged