Update tests for shipping methods
saleor/saleor-dashboard pull request #1820
Opened 2022-02-01 10:56 UTC by karola312

I want to merge this change because I added test for shipping zones bulk delete and updated tests for creating shipping zone and method

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://stable.staging.saleor.cloud/graphql/

2022-02-01 10:56 UTC, patrys commented
Task linked: [SALEOR-5502 Create missing tests for shipping methods](https://app.clickup.com/t/2549495/SALEOR-5502)

2022-02-02 09:21 UTC, dominik-zeglen approved these changes

2022-02-07 11:25 UTC, eCzerniak requested changes
Please check those tests.

2022-02-07 11:25 UTC, eCzerniak commented on cypress/integration/configuration/shippingMethods/postalCodes.js
> +  describe("As a user I want to create shipping method with postal codes", () => {
Those tests are failing. Probably some changes on UI were made. 
<img width="504" alt="image" src="https://user-images.githubusercontent.com/29308910/152779145-a2640b86-4a0d-401d-a304-bd06ec8f9eb4.png">

2022-02-08 11:52 UTC, eCzerniak approved these changes

2022-02-09 12:33 UTC, Kjaroszew commented on cypress/integration/configuration/shippingMethods/shippingWeights/shippingWeightsLimits.js
> -  describe("Shipping weight limits", () => {
This test fails during execution, probably changes to UI were made which resulted in error
![image](https://user-images.githubusercontent.com/97674352/153201496-f47a7fe7-5419-47bf-aa73-fe26fe3d667b.png)

2022-02-09 12:36 UTC, Kjaroszew commented on cypress/integration/configuration/shippingMethods/shippingWeights/weightRecalculate.js
> +  describe("As a staff user I want to change shop default weight unit", () => {
This test fails during execution, probably changes to UI were made which resulted in error
![image](https://user-images.githubusercontent.com/97674352/153202324-2900e2db-b5bb-4b62-b6fd-12909d501abe.png)

2022-02-09 12:40 UTC, Kjaroszew commented on cypress/integration/configuration/shippingMethods/channelsInShipping.js
> +  describe("As a staff user I want have different shipping method prices for each channel", () => {
This test fails during execution, probably changes to UI were made which resulted in error
![image](https://user-images.githubusercontent.com/97674352/153202943-6f4963ac-4ede-410c-b91c-94047ef3a613.png)

2022-02-09 12:55 UTC, Kjaroszew commented on cypress/integration/configuration/shippingMethods/createShippingMethod.js
> +  describe("As a staff user I want to create shipping zone and rate", () => {
This test fails during execution, probably changes to UI were made which resulted in error
![image](https://user-images.githubusercontent.com/97674352/153205412-0eaa4de6-3ad9-4a9f-a721-70bbc2bda366.png)

2022-02-09 14:11 UTC, Kjaroszew commented on cypress/integration/configuration/shippingMethods/editShippingMethod.js
> +  describe("As a user I should be able to update and delete shipping method", () => {
It seems that all found issues are similar in nature 
![image](https://user-images.githubusercontent.com/97674352/153212833-c623a1a0-4104-40e2-990e-db06be934813.png)

2022-02-09 14:55 UTC, Kjaroszew approved these changes
ok

2022-02-09 17:15 UTC, merged