Update tests for ordering products
saleor/saleor-dashboard pull request #1824
Opened 2022-02-02 13:09 UTC by karola312

I want to merge this change because I updated test for ordering products

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://stable.staging.saleor.cloud/graphql/

2022-02-02 13:09 UTC, patrys commented
Task linked: [SALEOR-5473 Update tests for order products](https://app.clickup.com/t/2549495/SALEOR-5473)

2022-02-03 13:36 UTC, bmigirl approved these changes

2022-02-10 09:53 UTC, eCzerniak requested changes
Also, those tests should be moved to order directory. If we marked them in our Saleor_Test_Suit as a part of orders then it should be moved there.
It can be like cypress/integration/

2022-02-10 09:53 UTC, eCzerniak commented on cypress/integration/checkout/stocksInCheckout.js
> +    it("should create checkout with last product in stock. TC: SALEOR_0404", () => {
Test case number is wrong.

2022-02-10 09:53 UTC, eCzerniak commented on cypress/integration/checkout/purchaseWithProductTypes.js
> +    it("should purchase multiple products with all product types. TC: SALEOR_0404", () => {
This test is failing because of wrong shippingMethodId.

2022-02-15 12:51 UTC, karola312 commented on cypress/integration/checkout/productWithoutShipping.js
> +  describe("Order product without shipping option", () => {
I change description, I won't be moving this spec now, because It will be moved in refactor to separate API tests form other tests

2022-02-15 12:55 UTC, karola312 commented on cypress/integration/checkout/stocksInCheckout.js
> +  describe("Manage products stocks in checkout", () => {
I changed name to "As an admin I want to have correct products stocks after checkout"

2022-02-16 13:44 UTC, eCzerniak approved these changes

2022-02-28 07:38 UTC, eCzerniak commented
@karola312  can it be merged or we are waiting for something with this PR?

2022-02-28 09:57 UTC, merged