Updated names for attributes tests on 3.0 according to guide  new
saleor/saleor-dashboard pull request #1838
Opened 2022-02-08 08:29 UTC by Kjaroszew

I want to merge this change because I need to resolve CLA issue

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://stable.staging.saleor.cloud/graphql/

2022-02-08 11:37 UTC, eCzerniak approved these changes

2022-02-11 08:57 UTC, jwm0 requested changes
You're updating the package-lock.json with node v16, we are still using v14. Please unstage package-lock changes and make sure you're on node 14 (I recommend using `nvm` for easy node version changes/installation: https://formulae.brew.sh/formula/nvm)

2022-02-15 12:18 UTC, Kjaroszew commented
currently i have versions: 
npm 6.14.15
node v14.18.3

npm i  command was executed to update "package-lock.json" file

2022-02-18 09:15 UTC, jwm0 approved these changes

2022-02-18 15:03 UTC, merged