removing hardcoded keys and adding  CYPRESS_RECORD_KEY  variable
saleor/saleor-dashboard pull request #1979
Opened 2022-04-07 14:24 UTC by Kjaroszew

I want to merge this change because i want to remove hardcoded keys

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2022-04-07 14:26 UTC, patrys commented
Task linked: [SALEOR-6505 Test new Keys settings for saleor tests](https://app.clickup.com/t/2549495/SALEOR-6505)

2022-04-11 06:49 UTC, michalina-graczyk approved these changes

2022-04-11 08:35 UTC, karola312 approved these changes

2022-04-11 08:38 UTC, karola312 requested changes

2022-04-11 08:38 UTC, karola312 commented on .github/workflows/e2e.yml
> +A
Remove

2022-04-11 09:00 UTC, Kjaroszew commented on .github/workflows/e2e.yml
> +A
DONE

2022-04-11 10:01 UTC, karola312 approved these changes

2022-04-12 11:06 UTC, merged