Change URI to URL postfix in env variables
saleor/saleor-dashboard pull request #2021
Opened 2022-04-27 13:01 UTC by dominik-zeglen

I want to merge this change because it improves environment variables names.

**PR intended to be tested with API branch:** main

### Screenshots
<img width="628" alt="Zrzut ekranu 2022-04-27 o 11 24 04" src="https://user-images.githubusercontent.com/6833443/165523804-83437ade-411d-4726-922d-873b050bab55.png">

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/

2022-04-27 16:31 UTC, NyanKiyoshi approved these changes

2022-10-12 18:54 UTC, dominik-zeglen commented
@andrzejewsky would you mind taking care of this?

2022-10-13 09:21 UTC, NyanKiyoshi requested changes

2022-10-13 09:21 UTC, NyanKiyoshi commented on package.json
> +    "@saleor/macaw-ui": "github:saleor/macaw-ui#9612762",
Use the full length hash to make the hash immutable (SHA1 collision)
```suggestion
    "@saleor/macaw-ui": "github:saleor/macaw-ui#961276259adba647e4f8652e5d069765deff8c02",
```

2022-12-23 15:34 UTC, closed without merging