Fix filtering by boolean attribute
saleor/saleor-dashboard pull request #2031
Opened 2022-05-04 19:35 UTC by Droniu

I want to merge this change because it fixes filtering products by boolean attr.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/

2022-05-04 19:35 UTC, patrys commented
Task linked: [SALEOR-5860 Boolean attribute - it is not possible filter by booleanAttr](https://app.clickup.com/t/2549495/SALEOR-5860)

2022-05-05 08:59 UTC, bmigirl requested changes

2022-05-05 08:59 UTC, bmigirl commented on src/products/views/ProductList/filters.ts
> +  const isBooleanValue = value.every(v => v === "true" || v === "false");
`val` at least

2022-05-05 14:19 UTC, orzechdev approved these changes

2022-07-07 08:23 UTC, merged