Fix flaky tests
saleor/saleor-dashboard pull request #2077
Opened 2022-06-02 13:43 UTC by karola312

I want to merge this change because I fixed few flaky tests.

Tests Fixed: 
should be able to remove product attribute from product type
should be able to display different price for each channel
should update collection
should go to the next page
should be able to delete several shipping zones on shipping zones list page

To test this PR run command:
npx cypress-repeat run -n 10 --spec "cypress/integration/configuration/shippingMethods/editShippingZone.js", "cypress/integration/products/productsList/pagination.js", "cypress/integration/catalog/collections.js", "cypress/integration/configuration/shippingMethods/channelsInShipping.js", "cypress/integration/configuration/productTypes/attributesInProduductTypes.js"

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/

2022-06-02 13:43 UTC, patrys commented
Task linked: [SALEOR-7125 Investigate flaky tests](https://app.clickup.com/t/2549495/SALEOR-7125)

2022-06-03 07:07 UTC, eCzerniak requested changes
should see correct amount of products per page. TC: SALEOR_2606 this test case sometimes fails 
<img width="681" alt="image" src="https://user-images.githubusercontent.com/29308910/171804388-a5bc9d2d-4b35-4db4-851f-b00e2f459eb7.png">

and this test should be able go to the next page on product list. TC: SALEOR_2605 
<img width="650" alt="image" src="https://user-images.githubusercontent.com/29308910/171804789-e36e458d-0c9f-45c1-a3f5-dcb6870e9194.png">

2022-06-03 12:06 UTC, eCzerniak approved these changes

2022-06-05 18:01 UTC, michalina-graczyk approved these changes

2022-06-06 08:47 UTC, karola312 commented on cypress/integration/discounts/vouchers/createVouchersWithLimits.js
> +          // Create new checkout as other not logged in customer - voucher should be available for other customer
No, I want here to check with voucher has been created with correct limit -> multiple customers can use it, but only once

2022-06-06 10:27 UTC, merged