Add rules of hooks
saleor/saleor-dashboard pull request #2131
Opened 2022-07-01 07:43 UTC by timuric

Tested not found pages:
http://localhost:9000/products/xxx/variant/add
http://localhost:9000/apps/custom/xxx
http://localhost:9000/collections/xxx
http://localhost:9000/categories/xxx

2022-07-01 07:51 UTC, patrys commented
Task linked: [SALEOR-6377 Use react-hooks plugin for eslint](https://app.clickup.com/t/2549495/SALEOR-6377)

2022-07-04 07:06 UTC, dominik-zeglen requested changes
Use node 14 and then install dependencies

2022-07-07 05:50 UTC, eCzerniak approved these changes

2022-07-07 09:19 UTC, Droniu approved these changes

2022-07-08 07:24 UTC, orzechdev approved these changes

2022-07-13 09:13 UTC, dominik-zeglen approved these changes

2022-07-13 09:13 UTC, merged