create simple product without sku
saleor/saleor-dashboard pull request #2188
Opened 2022-07-22 10:16 UTC by szczecha

I want to merge this change because it fixes test `SALEOR_2806 should create simple product without sku` 

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://marketplace-gray.vercel.app/

2022-07-22 10:16 UTC, patrys commented
Task linked: [SALEOR-7715 Fix test should create simple product without sku](https://app.clickup.com/t/2549495/SALEOR-7715)

2022-07-22 11:47 UTC, eCzerniak requested changes
Need to check after merging PR with fix from dev side.

2022-08-17 19:36 UTC, szczecha commented
> Need to check after merging PR with fix from dev side.

@eCzerniak fix for publishing products was merged and I rebased branch with main

2022-08-18 06:25 UTC, eCzerniak commented on cypress/e2e/products/productsWithoutSku/createProductWithoutSku.js
>        const name = `${startsWith}${faker.datatype.number()}`;
```suggestion
      const name = `${startsWith}${faker.datatype.number()}`;
      
```

2022-08-18 06:37 UTC, eCzerniak approved these changes
Please consider my comments. Besides that it is ok.

2022-08-18 06:37 UTC, eCzerniak commented on cypress/e2e/products/productsWithoutSku/createProductWithoutSku.js
>            createWaitingForCaptureOrder({
```suggestion
          createWaitingForCaptureOrder({
             channelSlug: defaultChannel.slug,
             email: "example@example.com",
             variantsList: variants,
             shippingMethodName: shippingMethod.name,
             address,
            })
              .its("order.id")
              .should("be.ok");;
```

2022-08-18 09:27 UTC, karola312 approved these changes

2022-08-19 06:46 UTC, merged