Drop "manage products" permission requirement to view orders
saleor/saleor-dashboard pull request #2248
Opened 2022-08-19 10:35 UTC by dominik-zeglen

I want to merge this change because before this fix users without "manage products" were unable to view draft orders.

**PR intended to be tested with API branch:** main

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://marketplace-gray.vercel.app/

2022-08-19 10:35 UTC, patrys commented
Task linked: [SALEOR-7916 Permissions - manage orders - user cannot add products to order.](https://app.clickup.com/t/2549495/SALEOR-7916)

2022-08-22 09:45 UTC, Droniu approved these changes

2022-08-22 10:30 UTC, orzechdev requested changes

2022-08-22 13:03 UTC, dominik-zeglen commented on src/orders/components/OrderDraftDetailsProducts/useLineAlerts.ts
> +        product: { isAvailableForPurchase },
Resolver gets channel from its context so if draft order is created in Channel A, then it's `isAvailableForPurchase` points to its availability in Channel A.

2022-08-22 13:06 UTC, orzechdev commented on src/orders/components/OrderDraftDetailsProducts/useLineAlerts.ts
> +        product: { isAvailableForPurchase },
Ok then 👍

2022-08-22 13:06 UTC, orzechdev approved these changes

2022-08-25 08:35 UTC, merged