Introduce testing tools
saleor/saleor-dashboard pull request #2361
Opened 2022-10-07 10:56 UTC by orzechdev

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://marketplace-gray.vercel.app/

### Do you want to run more stable tests?
Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation

CONTAINERS=1

2022-10-07 10:56 UTC, patrys commented
Task linked: [SALEOR-8074 Introduce testing tools](https://app.clickup.com/t/2549495/SALEOR-8074)

2022-10-07 14:08 UTC, NyanKiyoshi requested changes

2022-10-07 14:14 UTC, orzechdev commented on .github/workflows/test-e2e-on-deploy.yml
> +            }
I'm not sure, for now, I just only moved this code to the other file to clean a bit CI

2022-10-13 09:09 UTC, orzechdev commented on .github/workflows/test-e2e-on-deploy.yml
> +            }
I think `removedPullRequestBodyBeforeTests[1].split(...)` may raise an error if `removedPullRequestBodyBeforeTests < 0` then split doesn't exist.

2022-10-13 10:25 UTC, NyanKiyoshi approved these changes

2022-10-13 10:44 UTC, Droniu approved these changes

2022-10-14 09:53 UTC, karola312 commented
After separating the deploy job and cypress test job, currently, in the cypress test job we are waiting ~7 minutes for the deployment to finish. It will be additional 7 minutes after every push in all of saleor-dashboard PRs. As far as I know, we are paying for time in these jobs. Before these changes, deployment, and tests, in one job took 18min, after changes we have two jobs that took 9 and 18 minutes. Is that ok for you @patrys , @michalina-graczyk

2022-10-14 11:48 UTC, patrys commented
@karola312 We could also use https://github.com/marketplace/actions/wait-for-deployment to wait for a deployment to finish.

2022-10-14 12:04 UTC, karola312 commented
But it still will be a job, which is doing nothing else than waiting for other job to finish for few minutes. Maybe after deployment, we should send a request (/repos/saleor/saleor-dashboard/dispatches), which will trigger the cypress job?

2022-10-17 09:19 UTC, orzechdev commented
@patrys It is possible, but we will need a little bit tricky workaround, similar to https://github.com/orgs/community/discussions/25220#discussioncomment-3246922 or use https://github.com/marketplace/actions/get-current-pull-request

2022-10-17 09:39 UTC, patrys commented
I think it still beats paying for several minutes of a worker spinning idly.

2023-01-23 16:03 UTC, closed without merging