Fix tests for pages
saleor/saleor-dashboard pull request #2366
Opened 2022-10-11 09:01 UTC by karola312

I want to merge this change because it fixes flaky tests for pages

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://marketplace-gray.vercel.app/

### Do you want to run more stable tests?
Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation

CONTAINERS=1

2022-10-11 09:01 UTC, patrys commented
Task linked: [SALEOR-8133 [Fix] Tests for pages](https://app.clickup.com/t/2549495/SALEOR-8133)

2022-10-17 10:42 UTC, eCzerniak requested changes
Those tests are failing
```
should create page with RICH_TEXT attributefailed
should create page with BOOLEAN attributeactive
should create page with NUMERIC attribute
```
with message: 
`{"data":{"attributeCreate":{"attribute":null,"errors":[{"field":"values","message":"Values cannot be used with input type boolean/numeric/rich-text."}]}},"extensions":{"cost":{"requestedQueryCost":100,"maximumAvailable":50000}}}`

2022-10-17 11:02 UTC, szczecha commented
> Those tests are failing
> 
> ```
> should create page with RICH_TEXT attributefailed
> should create page with BOOLEAN attributeactive
> should create page with NUMERIC attribute
> ```
> 
> with message: `{"data":{"attributeCreate":{"attribute":null,"errors":[{"field":"values","message":"Values cannot be used with input type boolean/numeric/rich-text."}]}},"extensions":{"cost":{"requestedQueryCost":100,"maximumAvailable":50000}}}`

@eCzerniak you ran those against v37? or main? The provided error was fixed on main https://github.com/saleor/saleor-dashboard/pull/2355 due to backend changes.

2022-10-20 07:20 UTC, eCzerniak approved these changes

2022-10-20 11:32 UTC, merged