Edit variant name on variant edit/create
saleor/saleor-dashboard pull request #2388
Opened 2022-10-17 12:03 UTC by krzysztofzuraw

I want to merge this change to fix #2000. I've added:
* required text input to change the name for both edit & create variant forms
* logic to change `Variant Name` based on `Variant Selection Attributes`
* validation logic on frontend side (the same pattern as in product create)

## Screenshots

Before
---
![CleanShot 2022-10-17 at 14 07 50@2x](https://user-images.githubusercontent.com/9116238/196173194-087117c9-f7b0-4b20-af4e-a7588addea2e.jpg)
![CleanShot 2022-10-17 at 14 08 15@2x](https://user-images.githubusercontent.com/9116238/196173254-f5613a30-6168-4415-8fa4-2181c9be6f53.jpg)

After
---
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/9116238/196173058-4bc544fe-5a6f-4557-b8c9-6737b47c3290.png">
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/9116238/196173106-235296bb-4ce2-4a10-8061-a5c8dc19a16a.png">
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/9116238/196367377-23815357-d47a-4937-875a-9001a4d3f5f5.png">

### Pull Request Checklist

1. [x] This code contains UI changes
2. [x] All visible strings are translated with proper context including data-formatting
3. [x] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [x] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://marketplace-gray.vercel.app/

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation

CONTAINERS=1

2022-10-17 12:03 UTC, patrys commented
Task linked: [SALEOR-6587 Edit variant name](https://app.clickup.com/t/2549495/SALEOR-6587)

2022-10-18 09:36 UTC, Droniu approved these changes

2022-10-19 15:28 UTC, Droniu approved these changes

2022-10-20 08:12 UTC, andrzejewsky approved these changes

2022-10-20 08:12 UTC, andrzejewsky commented on src/products/components/ProductVariantName/ProductVariantName.tsx
> +const ProductVariantName = ({ value, onChange, disabled, errors }: Props) => {
please use the same convention to define prop types, everywhere else we use FC

2022-10-20 08:12 UTC, andrzejewsky commented on src/products/components/ProductVariantCreatePage/form.tsx
> +    handleChange({ target: { value, name: "name" } });
just to comment: don't hesitate to refactor big components. You can spot many of them in our codebase, but they can be decoupled into smaller units where one component/hook means one responsibility. If you feel you can do it, please do - it always makes code more testable and readable

2022-10-20 09:21 UTC, Droniu submitted a review, later dismissed

2022-10-20 09:23 UTC, andrzejewsky submitted a review, later dismissed

2022-10-21 07:53 UTC, eCzerniak submitted a review, later dismissed

2022-10-21 08:02 UTC, eCzerniak submitted a review, later dismissed

2022-10-21 08:09 UTC, andrzejewsky approved these changes

2022-10-21 12:13 UTC, eCzerniak approved these changes

2022-10-21 13:40 UTC, Droniu requested changes

2022-10-21 13:40 UTC, Droniu commented on src/products/components/ProductVariantName/ProductVariantName.tsx
> +interface Props {
```suggestion
interface ProductVariantNameProps {
```

2022-10-21 13:40 UTC, Droniu commented on src/products/components/ProductVariantName/ProductVariantName.tsx
> +const ProductVariantName: React.FC<Props> = ({
```suggestion
const ProductVariantName: React.FC<ProductVariantNameProps> = ({
```

2022-10-21 13:40 UTC, Droniu commented on src/products/utils/validation.ts
> +};
I don't get it, why are you spreading an empty array?
```suggestion
export const validateVariantData = (
  data: ProductVariantCreateData | ProductVariantUpdateSubmitData,
): ProductErrorWithAttributesFragment[] => (
  !data.name ? [createEmptyRequiredError("name")] : [];
);
```

2022-10-24 09:39 UTC, eCzerniak approved these changes

2022-10-25 08:08 UTC, andrzejewsky approved these changes

2022-10-25 12:19 UTC, merged