feat: take API_URI from window object
saleor/saleor-dashboard pull request #2473
Opened 2022-10-26 13:43 UTC by krzysztofzuraw

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants

CONTAINERS=1

2022-10-26 13:54 UTC, andrzejewsky requested changes

2022-10-26 13:54 UTC, andrzejewsky commented on src/config.ts
> +export const API_URI = window.__SALEOR_CONFIG__.API_URI;
export a function instead of const eg. getApiUrl, then use it everywhere, function allows us to implement some url resolving strategies afterwards

2022-11-02 07:55 UTC, Droniu approved these changes
I like the ida. Can we get some comments how to use dynamic api uri? Also probably we need readme changes if we depracate the old way

2022-11-02 10:13 UTC, andrzejewsky approved these changes

2022-11-03 08:49 UTC, merged