Disable test for weight recalculate 3.6
saleor/saleor-dashboard pull request #2481
Opened 2022-10-26 15:36 UTC by karola312

I want to merge this change because... It's cherry-picked from https://github.com/saleor/saleor-dashboard/pull/2476

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants

CONTAINERS=1

2022-10-26 17:54 UTC, szczecha approved these changes

2022-10-27 06:16 UTC, krzysztofzuraw requested changes

2022-10-27 06:16 UTC, krzysztofzuraw commented on cypress/e2e/configuration/shippingMethods/shippingWeights/weightRecalculate.js
> +  xit(
```suggestion
  it.skip(
```
I think it  will be more readable that we skip the test and it is not a typo.

2022-10-27 12:13 UTC, eCzerniak approved these changes

2022-10-27 12:36 UTC, merged