Macaw UI update
saleor/saleor-dashboard pull request #2512
Opened 2022-11-02 10:16 UTC by Cloud11PL

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants

CONTAINERS=1

2022-11-02 15:15 UTC, andrzejewsky commented on package.json
> +    "@saleor/macaw-ui": "0.6.7",
keep it linked on this branch

2022-11-21 13:55 UTC, NyanKiyoshi requested changes

2022-11-21 13:55 UTC, NyanKiyoshi commented on package.json
> +    "@saleor/macaw-ui": "git@github.com:saleor/macaw-ui.git#3337aa0",
Use full hash, short hash is dangerous

2022-11-21 19:05 UTC, szczecha commented
- [ ] Should an eye icon have a frame? ![image](https://user-images.githubusercontent.com/30683248/203129950-5c0a3ab7-c744-486f-81e9-8ec26927cf34.png)

- [ ] Shouldn't back be a secondary button? 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/30683248/203131373-78dad058-be0e-4544-88cf-5aedb8907ab3.png">

- [ ] a lot of empty space between the filters 
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/30683248/203131959-415da2e7-cf0f-42ea-b4b9-b2abd9bb708e.png">

- [ ] The search input should be the same height as the buttons 
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/30683248/203132451-48c135a0-5335-4fd8-93e3-4b54c1ce43fc.png">

- [ ] Edit staff user, dark mode, default avatar does not have initials
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/30683248/203133672-ccd65501-b2b5-4053-bb32-4611af8ea2dd.png">

- [ ] Different alignment of metadata inputs (e.g. views: clients, products)
![image](https://user-images.githubusercontent.com/30683248/203137462-1b16dbee-6930-40c2-9ba7-44945703df55.png)

2022-11-22 08:47 UTC, szczecha commented
- [ ] Inconsistency in checkboxes colors
![image](https://user-images.githubusercontent.com/30683248/203267440-89c534a8-a145-4646-a3b4-34a06cd93ac2.png)
Controls form 0.6.7 macawUI
<img width="835" alt="image" src="https://user-images.githubusercontent.com/30683248/203267745-d1fbd3e5-be84-4c95-b758-5e4156946f70.png">

2022-11-22 13:48 UTC, karolm-saleor commented
Another thing that comes to mind here is ponglish.
If we choose one particular language all the suggestions and names should match the same language

2022-11-22 14:03 UTC, karolm-saleor commented
- [ ] When I enter Catalog - Products and select the first one on black mode eveytime the view is visible for 2 second then after a moment it crashes
![Screenshot 2022-11-22 at 15 01 54](https://user-images.githubusercontent.com/117726439/203333442-ca375af2-8f5c-4d18-b5cf-8d765239b502.png)

2022-11-23 12:54 UTC, krzysztofzuraw approved these changes

2022-11-23 16:45 UTC, NyanKiyoshi submitted a review, later dismissed

2022-11-24 07:56 UTC, NyanKiyoshi approved these changes
Only reviewed non .ts(x) files

2022-11-24 12:16 UTC, merged