[cypress] SALEOR-1009 Delete several gift cards
saleor/saleor-dashboard pull request #2646
Opened 2022-11-22 13:43 UTC by karolm-saleor

Autotest for SALEOR-1009
Delete several Gift Cards

2022-11-22 13:43 UTC, patrys commented
Task linked: [CLOUD-190 Switch to new flow after agreement](https://app.clickup.com/t/2549495/CLOUD-190)

2022-11-23 07:36 UTC, michalina-graczyk requested changes

2022-11-23 07:36 UTC, michalina-graczyk commented on cypress/e2e/catalog/giftCards/updatingGiftCards.js
> +      const name = `${startsWith}${faker.datatype.number()}`;
what is the name for? please add more detailed name

2022-11-23 07:36 UTC, michalina-graczyk commented on cypress/e2e/catalog/giftCards/updatingGiftCards.js
> +      const name2 = `${startsWith}${faker.datatype.number()}`;
Please don't use name2, it doesn't say much

2022-11-23 07:36 UTC, michalina-graczyk commented on cypress/e2e/catalog/giftCards/updatingGiftCards.js
> +  it.skip(
Why is it skipped?

2022-11-23 07:36 UTC, michalina-graczyk commented on cypress/e2e/catalog/giftCards/updatingGiftCards.js
> +  it.skip(
same here

2022-11-23 07:36 UTC, michalina-graczyk commented on cypress/e2e/catalog/giftCards/updatingGiftCards.js
> +            .should("not.be.visible");
I am afraid that this assertion might be not enough, can we check via API if there is null in response?

2022-11-23 08:28 UTC, eCzerniak requested changes

2022-11-23 08:28 UTC, eCzerniak commented on cypress/e2e/catalog/giftCards/updatingGiftCards.js
> +            .get(PRODUCTS_LIST.filters.filterBy.currency)
I don't think that using filter by currency is a good way. Someone else can use it and how we will now that we are removing proper giftCards?

2022-11-23 10:03 UTC, karola312 requested changes

2022-11-23 10:03 UTC, karola312 commented on cypress/elements/catalog/products/products-list.js
> +    filterOptionField: "[class^=FilterOptionField]",
If its possible avoid using classes, it would be better if you add and use data-test-id

2022-11-23 11:18 UTC, michalina-graczyk commented on cypress/e2e/catalog/giftCards/updatingGiftCards.js
> +            .get("tr")
Definitely we shouldn't use 'tr'

2022-12-01 12:43 UTC, szczecha commented on cypress/e2e/catalog/giftCards/updatingGiftCards.js
> +          cy.log(hash.id);
I think that you can remove cy.log

2022-12-01 12:43 UTC, szczecha commented on cypress/e2e/catalog/giftCards/updatingGiftCards.js
> +          cy.log(hash2.id);
I think that you can remove cy.log

2022-12-01 12:43 UTC, szczecha approved these changes

2022-12-01 13:12 UTC, szczecha approved these changes

2022-12-02 09:17 UTC, karola312 approved these changes

2022-12-02 09:35 UTC, michalina-graczyk approved these changes

2022-12-02 09:37 UTC, merged