Fix products filtering
saleor/saleor-dashboard pull request #2746
Opened 2022-11-29 14:06 UTC by orzechdev

Instead of just passing `attributes` in the query params I changed it into explicitly typed query params `boolean-attributes`, `date-attributes`, `datetime-attributes`, `numeric-attributes`, `string-attributes`. That way we can walk around the parsing issues e.g. https://github.com/saleor/saleor-dashboard/issues/2673#issuecomment-1327683202. We shouldn't guess what is the type of attribute based on its value - e.g. "2022" may be parsed as year, number or string, but it should be exactly equal to the type that core expects, the type of underneath attribute.

Fixes https://github.com/saleor/saleor-dashboard/issues/2673, https://github.com/saleor/saleor-dashboard/issues/2326.

It may not be an ideal solution, but filters are planned to be rebuilt. Please share your thoughts what do you think.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [x] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

2022-12-01 12:18 UTC, andrzejewsky requested changes

2022-12-01 12:18 UTC, andrzejewsky commented on src/products/views/ProductList/filters.ts
> +
Please write for these functions unit tests

2022-12-01 12:18 UTC, andrzejewsky commented on src/products/views/ProductList/filters.ts
> +};
Please write unit tests for this

2022-12-05 13:22 UTC, andrzejewsky approved these changes

2022-12-05 13:34 UTC, krzysztofzuraw approved these changes

2022-12-08 14:10 UTC, szczecha approved these changes

2022-12-09 14:19 UTC, merged