Remove submitting from exit dirty form modal
saleor/saleor-dashboard pull request #2820
Opened 2022-12-08 09:49 UTC by Droniu

I want to merge this change because it removes saving option form exit dirty form modal.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

2022-12-12 07:51 UTC, krzysztofzuraw approved these changes

2022-12-12 10:11 UTC, andrzejewsky requested changes

2022-12-12 10:11 UTC, andrzejewsky commented on src/components/Form/ExitFormDialog.tsx
>      <Dialog className={classes.container} open={isOpen} onClose={onClose}>
write unit test for it, at least for critical path

2022-12-14 07:45 UTC, krzysztofzuraw commented on src/components/Form/ExitFormDialog.test.tsx
> +    const button = getByTestId("ignore-changes");
**suggestion**: according to [RTL](https://testing-library.com/docs/user-event/intro) documentation it seems like a way of testing user interactions

```suggestion
		import userEvent from "@testing-library/user-event";
		// the rest of the test
		const user = userEvent.setup()
    await user.click(getByTestId("ignore-changes"));
```

2022-12-15 14:58 UTC, krzysztofzuraw approved these changes

2022-12-16 09:07 UTC, andrzejewsky approved these changes

2022-12-16 14:54 UTC, merged