[WIP] Setting open-graph
saleor/saleor-dashboard pull request #2824
Opened 2022-12-08 14:20 UTC by andrzejewsky

Closes: https://github.com/saleor/saleor-dashboard/issues/2823

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

2022-12-19 11:05 UTC, timuric commented
Title
`Saleor Login | Sign in to the Saleor Dashboard`
Description 
`Sign in to the Saleor Dashboard to manage your orders, payments, products and more.`

Image
![og-dashboard](https://user-images.githubusercontent.com/4006792/208412204-57663aec-f8a2-46de-b277-229d95df3169.png)

2022-12-22 14:08 UTC, krzysztofzuraw submitted a review, later dismissed

2022-12-23 15:17 UTC, NyanKiyoshi approved these changes

2022-12-29 08:59 UTC, Droniu submitted a review, later dismissed

2023-01-12 10:56 UTC, mirekm commented
Let's update the image.

2023-01-12 11:43 UTC, mirekm commented
New image

<img width="1200" alt="saleor-dashboard-og" src="https://user-images.githubusercontent.com/249912/212058039-904798a7-c46f-44c1-9aaa-627e748410d8.png">

2023-01-12 11:46 UTC, mirekm requested changes

2023-01-12 11:46 UTC, mirekm commented on src/index.html
>      <title>Saleor e-commerce</title>
Please also update the title accordingly

2023-01-17 11:59 UTC, karolm-saleor approved these changes
✓ QA Passed

2023-01-17 13:01 UTC, krzysztofzuraw submitted a review, later dismissed

2023-01-17 13:02 UTC, poulch approved these changes

2023-01-17 13:25 UTC, Droniu submitted a review, later dismissed

2023-01-20 09:53 UTC, 8r2y5 submitted a review, later dismissed

2023-03-01 20:44 UTC, mirekm approved these changes

2023-03-02 07:44 UTC, krzysztofzuraw approved these changes

2023-03-08 09:13 UTC, andrzejewsky commented
closed in: https://staging-demo.saleor.io/dashboard/c

2023-03-08 09:13 UTC, closed without merging