Hide toolbar in app page
saleor/saleor-dashboard pull request #2938
Opened 2023-01-03 12:23 UTC by orzechdev

I want to merge this change because it hides toolbar in app page. App iframe now also takes all available space in window (or at least 60vh).

**PR intended to be tested with API branch:** 

### Screenshots

<img width="1262" alt="Screenshot 2023-01-03 at 13 11 22" src="https://user-images.githubusercontent.com/9825562/210356476-a4ddcc72-e1d0-4df1-b168-9eebf40baf0e.png">

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

2023-01-09 09:50 UTC, lkostrowski commented
@orzechdev lets remove "Apps" back button. We don't need it, we have navigation link

2023-01-09 09:58 UTC, lkostrowski requested changes
Code is ok, lets just remove "Apps" back button, we don't need it anyway and it takes space.

Also the top bar can be a little smaller, but its not a blocker - we will remove it soon anyway

2023-01-09 10:39 UTC, poulch approved these changes

2023-01-10 09:31 UTC, szczecha approved these changes

2023-01-10 14:24 UTC, merged