Fix test related to saving variant
saleor/saleor-dashboard pull request #2962
Opened 2023-01-09 14:56 UTC by szczecha

I want to merge this change because it fixes https://github.com/saleor/saleor-dashboard/issues/2956 

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?
To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

2023-01-11 09:30 UTC, karolm-saleor requested changes

2023-01-11 17:01 UTC, szczecha commented on cypress/elements/catalog/products/variants-selectors.js
> +  skuInput: "[name='sku']",
Well, it should be added in macawUI to work correctly, I cannot access this input from the dashboard repo. 
<img width="382" alt="image" src="https://user-images.githubusercontent.com/30683248/211860912-7c1c8a00-6e4f-4ae7-880f-1fd01d6a08ee.png">

I added data-test-id in the only possible place right now but it required adding an extra wait for one of the requests.

2023-01-12 07:23 UTC, karolm-saleor commented on cypress/elements/catalog/products/variants-selectors.js
> +  skuInput: "[name='sku']",
How come adding a data-test-id required an extra wait?
We can coordinate with dashboard dev team to add data-test-id in macawUI as that is an easy change and generally a good practice.

2023-01-12 07:28 UTC, szczecha commented on cypress/elements/catalog/products/variants-selectors.js
> +  skuInput: "[name='sku']",
![image](https://user-images.githubusercontent.com/30683248/212004281-a1e23447-0192-4e6b-bbad-4b3d7ee96240.png)

2023-01-12 13:22 UTC, karolm-saleor approved these changes

2023-01-13 08:21 UTC, merged