Uncover new apps marketplace
saleor/saleor-dashboard pull request #2993
Opened 2023-01-16 20:08 UTC by orzechdev

I want to merge this change because it uncovers new apps marketplace.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
APPS_MARKETPLACE_API_URI=https://marketplace-gray.vercel.app/api/v2/saleor-apps
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

2023-01-17 14:08 UTC, lkostrowski requested changes

2023-01-17 14:08 UTC, lkostrowski commented on .github/workflows/deploy-demo-staging.yaml
> +      APPS_MARKETPLACE_API_URI: "https://apps.saleor.io/api/v2/saleor-apps"
Staging -> `https://marketplace-gray.vercel.app/api/v2/saleor-apps`

2023-01-17 14:08 UTC, lkostrowski commented on .github/workflows/deploy-staging.yaml
> +      APPS_MARKETPLACE_API_URI: "https://apps.saleor.io/api/v2/saleor-apps"
Staging -> `https://marketplace-gray.vercel.app/api/v2/saleor-apps`

2023-01-18 14:33 UTC, lkostrowski requested changes
Lets wait for https://github.com/saleor/saleor-dashboard/pull/2975

2023-01-19 12:04 UTC, poulch requested changes
LGTM, are you going to remove old apps dir ?

2023-01-19 12:04 UTC, poulch approved these changes

2023-01-19 12:11 UTC, lkostrowski commented
> LGTM, are you going to remove old apps dir ?

@poulch it will be removed in another PR, we don't want to delay release with a big code diff in the same PR

2023-01-19 12:17 UTC, NyanKiyoshi approved these changes
CIs: LGTM

2023-01-19 13:14 UTC, lkostrowski approved these changes

2023-01-19 13:15 UTC, merged