Fix rate limits in release tests
saleor/saleor-dashboard pull request #3106
Opened 2023-02-03 15:11 UTC by karola312

I want to merge this change because it will fix - https://github.com/saleor/saleor-dashboard/actions/runs/4082131921/jobs/7036155242

Rate limit increased to 1000

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
MARKETPLACE_URL=https://apps.saleor.io
APPS_MARKETPLACE_API_URI=https://marketplace-gray.vercel.app/api/v2/saleor-apps
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

2023-02-03 16:07 UTC, NyanKiyoshi requested changes

2023-02-03 16:07 UTC, NyanKiyoshi commented on .github/workflows/getEnvironmentVariables.js
> +  .option("--repo_token <token>", "token for login to cloud")
You removed `--token` but you are still passing `--token` + the help text is saying it's a "cloud" token whereas it's a GitHub token.

2023-02-08 08:15 UTC, NyanKiyoshi commented on .github/workflows/tests-nightly.yml
> +              --repo_token "$REPO_TOKEN"
`--token` is not defined in the script

2023-02-08 09:18 UTC, NyanKiyoshi approved these changes

2023-02-08 09:22 UTC, michalina-graczyk approved these changes

2023-02-08 09:22 UTC, merged