Add "testmo" config
saleor/saleor-dashboard pull request #3209
Opened 2023-02-22 14:14 UTC by michalina-graczyk

I want to merge this change because I wan to add integration between cypress tests and TestMo -> tool for test case management 

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

2023-02-22 14:18 UTC, wojteknowacki requested changes

2023-02-22 14:18 UTC, wojteknowacki commented on cypress.config.js
> +  },
Do we need it? Looks like the one below should be enough 🤔

2023-02-22 14:18 UTC, wojteknowacki commented on cypress/plugins/index.js
> -  // require("cypress-mochawesome-reporter/plugin")(on); - uncomment to run reports
It is not working with this commented? I think it should 🤔

2023-02-22 14:38 UTC, wojteknowacki approved these changes

2023-02-27 09:26 UTC, karola312 approved these changes

2023-02-27 09:31 UTC, merged