New product header
saleor/saleor-dashboard pull request #3346
Opened 2023-03-13 11:37 UTC by poulch

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps
SALEOR_APPS_ENDPOINT=https://apps.saleor.io/api/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

2023-03-13 16:54 UTC, krzysztofzuraw approved these changes

2023-03-14 09:16 UTC, andrzejewsky requested changes

2023-03-14 09:16 UTC, andrzejewsky commented on src/components/AppLayout/FilterBar/Filter.tsx
> +        return acc + (dataFilterElement.active ? 1 : 0);
**suggestion**: it deserves dedicated function, hard to read what this memo is doing

2023-03-14 09:16 UTC, andrzejewsky commented on src/components/AppLayout/FilterBar/styles.ts
> +);
**issue**: please don't use old macaw anymore in the newly created stuff, style with box or sprinkles

2023-03-14 09:16 UTC, andrzejewsky commented on src/products/components/ProductListTiles/ProductListTiles.tsx
> +        <Typography align="center">
**issue**: use our Text component

2023-03-14 09:16 UTC, andrzejewsky commented on src/products/components/ProductListDatagrid/ProductListDatagrid.tsx
> +        <div className={sprinkles({ paddingX: 9 })}>
**suggestion**: Box

2023-03-14 10:19 UTC, andrzejewsky approved these changes

2023-03-14 10:29 UTC, merged