Use Accordion component from new macaw
saleor/saleor-dashboard pull request #3712
Opened 2023-05-31 15:02 UTC by poulch

closes https://github.com/saleor/saleor-dashboard/issues/3704

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `data-test-id` are added for new elements
4. [ ] The changes are tested in Chrome/Firefox/Safari browsers and in light/dark mode
5. [ ] Your code works with the latest stable version of the core

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] giftCard
3. [ ] category
4. [ ] collection
5. [ ] attribute
6. [ ] productType
7. [ ] shipping
8. [ ] customer
9. [ ] permissions
10. [ ] menuNavigation
11. [ ] pages
12. [ ] sales
13. [ ] vouchers
14. [ ] homePage
15. [ ] login
16. [ ] orders
17. [ ] products
18. [ ] app
19. [ ] plugins
20. [ ] translations
21. [ ] navigation
22. [ ] variants
23. [ ] payments

CONTAINERS=1

2023-06-01 12:56 UTC, krzysztofzuraw approved these changes

2023-06-01 12:56 UTC, krzysztofzuraw commented on src/components/Timeline/TimelineEvent.tsx
> +            value="test"
**question**: do you need this value here?

2023-06-01 12:56 UTC, krzysztofzuraw commented on src/components/Timeline/TimelineEvent.tsx
> +          className={sprinkles({
**question**: we don't have `width` defined here? 🤔

2023-06-01 13:30 UTC, krzysztofzuraw submitted a review, later dismissed

2023-06-02 17:17 UTC, andrzejewsky approved these changes

2023-06-28 12:02 UTC, andrzejewsky submitted a review, later dismissed

2023-06-28 12:02 UTC, andrzejewsky commented on .changeset/beige-dots-protect.md
> +"saleor-dashboard": patch
minor

2023-06-29 10:17 UTC, krzysztofzuraw submitted a review, later dismissed

2023-07-03 13:24 UTC, wojteknowacki commented
When selecting filters user sees focus on grid which is underneath 

https://github.com/saleor/saleor-dashboard/assets/124166231/3f48d9b1-f12a-440b-a2bf-e74a5d506713

2023-07-03 13:27 UTC, wojteknowacki commented
The whole row could be clickable on filters - now only the txt field and radio button is clickable
![image](https://github.com/saleor/saleor-dashboard/assets/124166231/5f284ce7-ac52-4880-b3a4-bd7d32d702a8)

2023-07-03 13:31 UTC, wojteknowacki commented
Closing expanded filter field needs few click actions to work


https://github.com/saleor/saleor-dashboard/assets/124166231/e7048881-130e-4479-8a62-704f0d027a68

2023-07-04 12:10 UTC, michalina-graczyk commented
<img width="1482" alt="image" src="https://github.com/saleor/saleor-dashboard/assets/25908728/cba7de88-f661-4c6d-9173-ae2a9f4efdfb">

2023-07-04 12:13 UTC, michalina-graczyk commented
> The whole row could be clickable on filters - now only the txt field and radio button is clickable ![image](https://user-images.githubusercontent.com/124166231/250569738-5f284ce7-ac52-4880-b3a4-bd7d32d702a8.png)

I confirm. This is very unintuitive

2023-07-04 12:21 UTC, michalina-graczyk commented
![image](https://github.com/saleor/saleor-dashboard/assets/25908728/00f71e30-b0ee-4c78-b0e2-5a8030385ceb)

2023-07-04 12:25 UTC, michalina-graczyk commented
[Untitled_ Jul 4, 2023 2_23 PM.webm](https://github.com/saleor/saleor-dashboard/assets/25908728/ca57d18e-d54d-40c2-b3c2-b4f5710eeda0)
1. Go to orders
2. Go into random order details
3. Go to the order history
4. Click on the arrow - nothing happened

it looks like we implement a dead feature. What should happen when I click there?

2023-07-04 12:29 UTC, michalina-graczyk commented
![image](https://github.com/saleor/saleor-dashboard/assets/25908728/2b29a730-4f71-442e-8f16-42ae4137160a)
What is the first letter in the countries ?

2023-07-04 12:32 UTC, michalina-graczyk commented
`Timeline event use for example in order and gift card history` -> can't see it, am I on wrong view?

![image](https://github.com/saleor/saleor-dashboard/assets/25908728/31295625-123a-4acc-805a-af2011b853a0)
![image](https://github.com/saleor/saleor-dashboard/assets/25908728/26c6ad62-2160-49f2-92df-a8654573b30b)

2023-07-04 12:34 UTC, michalina-graczyk commented
`Product variant details - available channels`
How it should looks on this view? Current:
![image](https://github.com/saleor/saleor-dashboard/assets/25908728/c75748ea-0249-45df-becd-dbf328758b98)

2023-07-04 12:40 UTC, michalina-graczyk commented
![image](https://github.com/saleor/saleor-dashboard/assets/25908728/3f769b86-4988-4358-8b37-6d4d8affab35)

2023-07-04 12:51 UTC, michalina-graczyk requested changes
All changes are described in comments

2023-07-05 12:38 UTC, poulch commented
> <img alt="image" width="1482" src="https://user-images.githubusercontent.com/25908728/250897273-cba7de88-f661-4c6d-9173-ae2a9f4efdfb.png">

This is intentional that accordion content is indented compared to the accordion trigger, and this is how it works currently on staging.

2023-07-05 12:40 UTC, poulch commented
> > The whole row could be clickable on filters - now only the txt field and radio button is clickable ![image](https://user-images.githubusercontent.com/124166231/250569738-5f284ce7-ac52-4880-b3a4-bd7d32d702a8.png)
> 
> I confirm. This is very unintuitive

I've decided to not include Filter as it will be replaced be new component

2023-07-05 12:43 UTC, poulch commented
> ![image](https://user-images.githubusercontent.com/25908728/250898601-f63851d9-2704-4216-80e2-ac4a4a8f2487.png)

As I've described above, Filter is not part of this PR.

2023-07-05 13:19 UTC, poulch commented
> Untitled_.Jul.4.2023.2_23.PM.webm 
> 1. Go to orders
> 2. Go into random order details
> 3. Go to the order history
> 4. Click on the arrow - nothing happened
> 
> it looks like we implement a dead feature. What should happen when I click there?

This will be fixed in this PR

2023-07-05 13:21 UTC, poulch commented
> ![image](https://user-images.githubusercontent.com/25908728/250901281-2b29a730-4f71-442e-8f16-42ae4137160a.png) What is the first letter in the countries ?

This is not an accordion component but only looks similar. IMO we can migrate this component during whole page migration to new macaw

2023-07-05 13:27 UTC, poulch commented
> `Timeline event use for example in order and gift card history` -> can't see it, am I on wrong view?
> 
> ![image](https://user-images.githubusercontent.com/25908728/250901812-31295625-123a-4acc-805a-af2011b853a0.png) ![image](https://user-images.githubusercontent.com/25908728/250902008-26c6ad62-2160-49f2-92df-a8654573b30b.png)

You were in good view but not all history events have accordion.
Example for orders: https://3704-replace-accordion.dashboard.saleor.rocks/orders/T3JkZXI6YzkxZTQzMDMtOGNlOS00ZDRlLTk2OGYtMmZjMGI5NjdmMmIy
I coundn't found an example for gift card but this is the same component as in order history.

2023-07-05 13:29 UTC, poulch commented
> `Product variant details - available channels` How it should looks on this view? Current: ![image](https://user-images.githubusercontent.com/25908728/250902442-c75748ea-0249-45df-becd-dbf328758b98.png)

By ``Product variant details ` I mean this view: https://3704-replace-accordion.dashboard.saleor.rocks/products/UHJvZHVjdDo3Nw%3D%3D/variant/UHJvZHVjdFZhcmlhbnQ6MjE3

2023-07-05 13:29 UTC, poulch commented
> ![image](https://user-images.githubusercontent.com/25908728/250903825-3f769b86-4988-4358-8b37-6d4d8affab35.png)

Please create separate issue for this

2023-07-07 09:13 UTC, michalina-graczyk approved these changes

2023-07-10 08:18 UTC, andrzejewsky approved these changes

2023-07-10 08:24 UTC, merged