Ability to add products to unconfirmed orders
saleor/saleor-dashboard pull request #4101
Opened 2023-08-21 12:21 UTC by lephuongbg

closes #4099

Basically I copy pasted code from draft order implementation over to unconfirmed order page.

### Screenshots

Before

![image](https://github.com/saleor/saleor-dashboard/assets/1001176/59a07325-be90-488e-92bc-368568b5f944)

After

![image](https://github.com/saleor/saleor-dashboard/assets/1001176/5d10b023-2ad0-45c3-bad8-00df6a826d90)

### Pull Request Checklist

1. [x] This code contains UI changes
2. [x] All visible strings are translated with proper context including data-formatting
3. [x] Attributes `data-test-id` are added for new elements
4. [x] The changes are tested in Chrome/Firefox/Safari browsers and in light/dark mode
5. [x] Your code works with the latest stable version of the core
6. [x] I added changesets and [read good practices](../.changeset/README.md)

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] app
3. [ ] attribute
4. [ ] category
5. [ ] collection
6. [ ] customer
7. [ ] giftCard
8. [ ] homePage
9. [ ] login
10. [ ] menuNavigation
11. [ ] navigation
12. [ ] orders
13. [ ] pages
14. [ ] payments
15. [ ] permissions
16. [ ] plugins
17. [ ] productType
18. [ ] products
19. [ ] sales
20. [ ] shipping
21. [ ] translations
22. [ ] variants
23. [ ] vouchers

CONTAINERS=2

2023-08-22 07:31 UTC, Droniu submitted a review, later dismissed

2023-08-22 07:32 UTC, andrzejewsky requested changes
Thanks for PR!, I left one comment.

2023-08-22 07:32 UTC, andrzejewsky commented on .changeset/kind-apes-look.md
> +"saleor-dashboard": patch
since it's a new feature, it should be "minor"

2023-09-21 08:01 UTC, andrzejewsky commented
@lephuongbg Hey any update on it? Could you apply mentioned comment?

2023-09-21 11:50 UTC, lephuongbg commented
@andrzejewsky Thanks for the nudge. Updated the PR.

2023-09-27 10:23 UTC, andrzejewsky commented
@lephuongbg Hey I was reviewing your PR including some UI checks, seems like it causes an error when I try to add the product:


<img width="1379" alt="Screenshot 2023-09-27 at 11 17 07" src="https://github.com/saleor/saleor-dashboard/assets/7943292/271962d8-ac64-4904-956d-7c1d7378f4df">

2023-09-27 10:44 UTC, lephuongbg commented
@andrzejewsky Can I have the detailed graphql error response that you met?

2023-09-29 10:56 UTC, wojteknowacki commented
Hello @lephuongbg . Error message mentioned by @andrzejewsky :
`{
  "errors": [
    {
      "message": "Variable \"$isStaffUser\" of required type \"Boolean!\" was not provided.",
      "locations": [
        {
          "line": 1,
          "column": 34
        }
      ],
      "extensions": {
        "exception": {
          "code": "GraphQLError"
        }
      }
    }
  ]
}`

2023-11-21 01:49 UTC, closed without merging