Tag docker container as latest accordingly to the version
saleor/saleor-dashboard pull request #4241
Opened 2023-09-25 09:45 UTC by andrzejewsky

closes: https://github.com/saleor/saleor-dashboard/issues/4148

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `data-test-id` are added for new elements
4. [ ] The changes are tested in Chrome/Firefox/Safari browsers and in light/dark mode
5. [ ] Your code works with the latest stable version of the core
6. [ ] I added changesets and [read good practices](../.changeset/README.md)

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] app
3. [ ] attribute
4. [ ] category
5. [ ] collection
6. [ ] customer
7. [ ] giftCard
8. [ ] homePage
9. [ ] login
10. [ ] menuNavigation
11. [ ] navigation
12. [ ] orders
13. [ ] pages
14. [ ] payments
15. [ ] permissions
16. [ ] plugins
17. [ ] productType
18. [ ] products
19. [ ] sales
20. [ ] shipping
21. [ ] translations
22. [ ] variants
23. [ ] vouchers

CONTAINERS=2

2023-09-25 09:47 UTC, poulch approved these changes

2023-09-25 09:49 UTC, NyanKiyoshi requested changes

2023-09-25 09:49 UTC, NyanKiyoshi commented on .changeset/sour-sheep-rush.md
> +Tag docker container as latest when the new latest releae was published
Typo only:
```suggestion
Tag docker container as latest when the new latest release was published
```

Rewording for a clearer changelog:

```suggestion
Tag docker container as latest when the published GitHub release is marked as "latest"
```

2023-09-25 09:49 UTC, NyanKiyoshi commented on .github/workflows/publish-containers.yml
> +          LATEST_VERSION=$(gh api repos/saleor/saleor-dashboard/releases/latest | jq .tag_name | xargs)
```suggestion
          LATEST_VERSION=$(gh api repos/saleor/saleor-dashboard/releases/latest | jq -r .tag_name)
```

2023-09-25 09:49 UTC, NyanKiyoshi commented on .github/workflows/publish-containers.yml
> +          CONTAINER_TAGS=${{ steps.image.outputs.image_name }}:${VERSION_TAG}
If 1.2.3 is latest, we need to push:
- `:latest`
- `:1.2.3`

Currently it only pushes `:latest`

2023-09-26 13:28 UTC, NyanKiyoshi approved these changes

2023-09-26 23:39 UTC, Droniu approved these changes

2023-09-27 07:49 UTC, merged