[WIP] E2e pool
saleor/saleor-dashboard pull request #4350
Opened 2023-10-18 10:19 UTC by andrzejewsky

closes #...

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `data-test-id` are added for new elements
4. [ ] The changes are tested in Chrome/Firefox/Safari browsers and in light/dark mode
5. [ ] Your code works with the latest stable version of the core
6. [ ] I added changesets file (instructions in [contribution guide](https://github.com/saleor/saleor-dashboard/blob/main/.github/CONTRIBUTING.md)

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] app
3. [ ] attribute
4. [ ] category
5. [ ] collection
6. [ ] customer
7. [ ] giftCard
8. [ ] homePage
9. [ ] login
10. [ ] menuNavigation
11. [ ] navigation
12. [ ] orders
13. [ ] pages
14. [ ] payments
15. [ ] permissions
16. [ ] plugins
17. [ ] productType
18. [ ] products
19. [ ] sales
20. [ ] shipping
21. [ ] translations
22. [ ] variants
23. [ ] vouchers

CONTAINERS=2

2023-10-18 10:41 UTC, poulch submitted a review, later dismissed

2023-10-18 10:56 UTC, Droniu approved these changes

2023-10-25 08:26 UTC, andrzejewsky commented
Additional option from CLI needed, issu: https://github.com/saleor/cli/issues/700

2023-10-25 14:24 UTC, mmiszy commented on .github/workflows/e2e-pool.yml
> +        run: echo '{"token":"Token ${{ env.ACCESS_TOKEN }}","telemetry":"false","organization_slug":"saleor","organization_name":"Saleor"}' > ~/.config/saleor.json
This could lead to `ACCESS_TOKEN` leak as it's logged to the console.
It's only thanks to GitHub Actions secrets masking it wasn't revealed.

2023-11-02 08:26 UTC, wojteknowacki commented on .github/workflows/e2e-pool.yml
> +      - name: Generate
Could you use some more explicit name for this step?

2023-11-02 08:30 UTC, wojteknowacki commented on .github/workflows/e2e-pool.yml
> +      - name: Reload snapshot
```suggestion
      - name: Revert base snapshot
```

2023-11-09 10:00 UTC, wojteknowacki approved these changes

2023-11-09 11:22 UTC, NyanKiyoshi requested changes

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +          BACKUP_NAME=$(echo $BACKUPS | jq -r '.[0].name')
```suggestion
          BACKUP_ID=$(echo "$BACKUPS" | jq -r '.[0].key')
          BACKUP_VER=$(echo "$BACKUPS" | jq -r '.[0].saleor_version')
          BACKUP_NAME=$(echo "$BACKUPS" | jq -r '.[0].name')
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +        uses: rlespinasse/github-slug-action@v4
```suggestion
        uses: rlespinasse/github-slug-action@102b1a064a9b145e56556e22b18b19c624538d94 # v4.4.1
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +        uses: rlespinasse/github-slug-action@v4
```suggestion
        uses: rlespinasse/github-slug-action@102b1a064a9b145e56556e22b18b19c624538d94 # v4.4.1
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/remove-instance.yml
> +        uses: rlespinasse/github-slug-action@v4
```suggestion
        uses: rlespinasse/github-slug-action@102b1a064a9b145e56556e22b18b19c624538d94 # v4.4.1
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +          echo "POOL_INSTANCE=https://${{ env.GITHUB_HEAD_REF_SLUG_URL }}.staging.saleor.cloud" >> $GITHUB_OUTPUT
```suggestion
          echo "BASE_URL=${GITHUB_HEAD_REF_SLUG_URL}.dashboard.saleor.rocks" >> $GITHUB_OUTPUT
          echo "API_URI=https://${GITHUB_HEAD_REF_SLUG_URL}.staging.saleor.cloud/graphql/" >> $GITHUB_OUTPUT
          echo "POOL_NAME=${GITHUB_HEAD_REF_SLUG_URL}" >> $GITHUB_OUTPUT
          echo "POOL_INSTANCE=https://${GITHUB_HEAD_REF_SLUG_URL}.staging.saleor.cloud" >> $GITHUB_OUTPUT
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +          echo "::notice title=SNAPSHOT::backup_id=${{ steps.backup.outputs.BACKUP_ID }}, version=${{ steps.backup.outputs.BACKUP_VER }}, name=${{ steps.backup.outputs.BACKUP_NAME }}"
Follow best practices https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +      - uses: actions/checkout@v4
Can do a partial checkout as only `.github/actions` is being used:

```suggestion
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ./.github/actions
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +      - uses: actions/checkout@v4
```suggestion
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ./.github/actions
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +            --skip-webhooks-update
```suggestion
          npx saleor backup restore "$BACKUP_ID" \
            --environment="$INSTANCE_NAME" \
            --skip-webhooks-update
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +            --skip-webhooks-update
```suggestion
          npx saleor env create "$INSTANCE_NAME" \
            --project=project-for-pr-testing \
            --database=snapshot \
            --restore-from="$BACKUP_ID" \
            --saleor=saleor-master-staging \
            --domain="$INSTANCE_NAME" \
            --skip-restrict \
            --skip-webhooks-update
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +        run: aws s3 sync ./build/dashboard s3://${{ secrets.AWS_TEST_DEPLOYMENT_BUCKET }}/${{ needs.prepare_variables.outputs.BASE_URL  }}
```suggestion
      - name: Deploy to S3
        env:
          AWS_TEST_DEPLOYMENT_BUCKET: ${{ secrets.AWS_TEST_DEPLOYMENT_BUCKET }}
          BASE_URL: ${{ needs.prepare_variables.outputs.BASE_URL }}
        run: aws s3 sync ./build/dashboard "s3://${AWS_TEST_DEPLOYMENT_BUCKET}/${BASE_URL}"
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_TEST_CF_DIST_ID }} --paths "/${{ needs.prepare_variables.outputs.BASE_URL  }}/*"
```suggestion
      - name: Invalidate cache
        env:
          AWS_TEST_CF_DIST_ID: ${{ secrets.AWS_TEST_CF_DIST_ID }}
          BASE_URL: ${{ needs.prepare_variables.outputs.BASE_URL }}
        run: aws cloudfront create-invalidation --distribution-id "$AWS_TEST_CF_DIST_ID" --paths "/${BASE_URL}/*"
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +      - name: Build dashbaord
```suggestion
      - name: Build dashboard
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
Set and limit the permissions of the token to the minimum it needs

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +        uses: bobheadxi/deployments@v1
```suggestion
        uses: bobheadxi/deployments@88ce5600046c82542f8246ac287d0a53c461bca3 # v1.4.0
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +        uses: bobheadxi/deployments@v1
```suggestion
        uses: bobheadxi/deployments@88ce5600046c82542f8246ac287d0a53c461bca3 # v1.4.0
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
Set and limit the permissions of the token to the minimum it needs

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +        uses: bobheadxi/deployments@v1
```suggestion
        uses: bobheadxi/deployments@88ce5600046c82542f8246ac287d0a53c461bca3 # v1.4.0
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
Set and limit the permissions of the token to the minimum it needs

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_TEST_CF_DIST_ID }} --paths "/${{ needs.prepare_variables.outputs.BASE_URL  }}/*"
```suggestion
      - name: Invalidate cache
        env:
          AWS_TEST_CF_DIST_ID: ${{ secrets.AWS_TEST_CF_DIST_ID }}
          BASE_URL: ${{ needs.prepare_variables.outputs.BASE_URL }}
        run: aws cloudfront create-invalidation --distribution-id "$AWS_TEST_CF_DIST_ID" --paths "/${BASE_URL}/*"
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/e2e-instances.yml
> +        run: aws s3 sync ./build/storybook s3://${{ secrets.AWS_TEST_DEPLOYMENT_BUCKET }}/${{ needs.prepare_variables.outputs.BASE_URL  }}/storybook
```suggestion
      - name: Invalidate cache
        env:
          AWS_TEST_DEPLOYMENT_BUCKET: ${{ secrets.AWS_TEST_DEPLOYMENT_BUCKET }}
          BASE_URL: ${{ needs.prepare_variables.outputs.BASE_URL }}
        run: aws s3 sync ./build/storybook "s3://${AWS_TEST_DEPLOYMENT_BUCKET}/${BASE_URL}/storybook"
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/remove-instance.yml
> +      - uses: actions/checkout@v4
Can do a partial checkout as only `.github/actions` is being used:

```suggestion
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ./.github/actions
```

2023-11-09 11:22 UTC, NyanKiyoshi commented on .github/workflows/remove-instance.yml
> +        run: npx saleor env remove "${{ env.GITHUB_HEAD_REF_SLUG_URL }}" --force
```suggestion
          SALEOR_CLI_ENV: staging
        run: npx saleor env remove "$GITHUB_HEAD_REF_SLUG_URL" --force
```

2023-11-09 11:53 UTC, cmiacz approved these changes

2023-11-09 11:53 UTC, cmiacz commented on .github/workflows/test-env-cleanup.yml
> +name: Testing
Is it intentional? This name may be a bit confusing.

2023-11-10 12:30 UTC, NyanKiyoshi approved these changes

2023-11-10 13:34 UTC, wojteknowacki approved these changes

2023-11-10 13:34 UTC, Droniu approved these changes

2023-11-10 13:35 UTC, poulch approved these changes

2023-11-10 13:35 UTC, poulch commented on .github/workflows/pr-automation.yml
> +          token: ${{ secrets.STAGING_TOKEN }}
```suggestion
          token: ${{ secrets.STAGING_TOKEN }}
```

2023-11-10 13:39 UTC, merged