Send order lines in orderGrantRefundCreate mutation
saleor/saleor-dashboard pull request #4373
Opened 2023-10-25 10:13 UTC by poulch

closes https://github.com/saleor/saleor-dashboard/issues/4277

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `data-test-id` are added for new elements
4. [ ] The changes are tested in Chrome/Firefox/Safari browsers and in light/dark mode
5. [ ] Your code works with the latest stable version of the core
6. [ ] I added changesets file (instructions in [contribution guide](https://github.com/saleor/saleor-dashboard/blob/main/.github/CONTRIBUTING.md)

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] app
3. [ ] attribute
4. [ ] category
5. [ ] collection
6. [ ] customer
7. [ ] giftCard
8. [ ] homePage
9. [ ] login
10. [ ] menuNavigation
11. [ ] navigation
12. [ ] orders
13. [ ] pages
14. [ ] payments
15. [ ] permissions
16. [ ] plugins
17. [ ] productType
18. [ ] products
19. [ ] sales
20. [ ] shipping
21. [ ] translations
22. [ ] variants
23. [ ] vouchers

CONTAINERS=2

2023-10-30 08:28 UTC, andrzejewsky requested changes

2023-10-30 08:28 UTC, andrzejewsky commented on src/orders/components/OrderGrantRefundPage/OrderGrantRefundPage.tsx
> +                    }
suggestion: that's good candidate for separate function

2023-10-30 08:28 UTC, andrzejewsky commented on src/orders/components/OrderGrantRefundPage/reducer.ts
> +    });
suggestion: this entire map function can be lifted up and named accordingly to what it does

2023-10-30 08:28 UTC, andrzejewsky commented on src/orders/components/OrderGrantRefundPage/reducer.ts
> +    });
issue: this almost completely copy pasted, the only difference is `line.orderLine.unitPrice.gross.amount`

2023-10-30 09:49 UTC, andrzejewsky approved these changes

2023-10-30 10:42 UTC, witoszekdev commented
@poulch The `OrderGrantRefundCreateLineInput` has a `reason` field as well, aka you can provide a reason for each field separately, like this:

```json
{
  "lines": [{"reason": "..." }],
  "reason": ""
}
```

Will we support this in the next PR, or am I missing something?

2023-10-30 10:57 UTC, poulch commented
> @poulch The `OrderGrantRefundCreateLineInput` has a `reason` field as well, aka you can provide a reason for each field separately, like this:
> 
> ```json
> {
>   "lines": [{"reason": "..." }],
>   "reason": ""
> }
> ```
> 
> Will we support this in the next PR, or am I missing something?

Currently, the UI does not allow the user to add a reason to each line. However, we can address this issue separately since it requires UI redesign.

2023-10-30 11:09 UTC, Droniu approved these changes

2023-10-30 11:11 UTC, witoszekdev approved these changes

2023-10-30 11:11 UTC, witoszekdev submitted a review, later dismissed

2023-10-31 13:29 UTC, wojteknowacki commented
Adjust currency marks in refund amount input
<img width="391" alt="Zrzut ekranu 2023-10-31 o 14 28 21" src="https://github.com/saleor/saleor-dashboard/assets/124166231/9f0aa00f-283d-45f2-be31-9d1636b6a554">

2023-10-31 13:49 UTC, wojteknowacki commented
Switching back the refund toggle should be enough to save the edited refund


https://github.com/saleor/saleor-dashboard/assets/124166231/cd6acdfe-4432-4397-a72d-12fc75c31cd6

2023-10-31 13:56 UTC, wojteknowacki commented
Error when refunding only shipping
<img width="1430" alt="Zrzut ekranu 2023-10-31 o 14 56 00" src="https://github.com/saleor/saleor-dashboard/assets/124166231/1b9b19e5-cfdf-4433-9f58-79d88dad567c">

2023-11-02 10:48 UTC, wojteknowacki approved these changes

2023-11-02 11:39 UTC, Droniu approved these changes

2023-11-02 11:43 UTC, merged