Use CLI for cleaning environments
saleor/saleor-dashboard pull request #4374
Opened 2023-10-25 11:12 UTC by karola312

Use CLI in order to clean environments (release environments and master weekly, automation dashboard every night)
### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `data-test-id` are added for new elements
4. [ ] The changes are tested in Chrome/Firefox/Safari browsers and in light/dark mode
5. [ ] Your code works with the latest stable version of the core
6. [ ] I added changesets file (instructions in [contribution guide](https://github.com/saleor/saleor-dashboard/blob/main/.github/CONTRIBUTING.md)

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] app
3. [ ] attribute
4. [ ] category
5. [ ] collection
6. [ ] customer
7. [ ] giftCard
8. [ ] homePage
9. [ ] login
10. [ ] menuNavigation
11. [ ] navigation
12. [ ] orders
13. [ ] pages
14. [ ] payments
15. [ ] permissions
16. [ ] plugins
17. [ ] productType
18. [ ] products
19. [ ] sales
20. [ ] shipping
21. [ ] translations
22. [ ] variants
23. [ ] vouchers

CONTAINERS=2

2023-10-25 14:06 UTC, NyanKiyoshi requested changes

2023-10-25 14:06 UTC, NyanKiyoshi commented on .github/workflows/clean-envs.yml
> +        run: echo '{"token":"Token ${{ env.ACCESS_TOKEN }}","telemetry":"false","organization_slug":"saleor","organization_name":"Saleor"}' > ~/.config/saleor.json
Use `jq` to build JSON from arbitrary values:

```suggestion
        run: jq --null-input --arg token "Token $ACCESS_TOKEN" '{"token": $token }", "telemetry": "false", "organization_slug": "saleor", "organization_name": "Saleor"}' > ~/.config/saleor.json
```

2023-10-25 14:06 UTC, NyanKiyoshi commented on .github/workflows/cleanEnvironments.js
> +  const envList = result.stdout.replace("\x1B[?25l\x1B[?25h", "");
Can you add comment on what you are doing here? (the ascii escape part: `\x1B[?25l\x1B[?25h` - which is probably hiding and showing the cursor)

Does saleor-cli have a pipe mode or CI mode so we don't need to remove the ASCII escapes?

2023-10-25 14:06 UTC, NyanKiyoshi commented on .github/workflows/cleanEnvironments.js
> +      );
Use `child_process.execFile(file[, args][, options][, callback])` instead, `child_process.exec(command[, options][, callback])` is not designed for handling unsanitized arguments

2023-10-25 14:06 UTC, NyanKiyoshi commented on .github/workflows/tests-nightly.yml
> +        run: echo '{"token":"Token ${{ env.ACCESS_TOKEN }}","telemetry":"false","organization_slug":"saleor","organization_name":"Saleor"}' > ~/.config/saleor.json
Use `jq` instead

2023-10-26 09:13 UTC, andrzejewsky commented on .github/workflows/cleanEnvironments.js
> +    console.log(snapshotsForRestore);
mistake?

2023-11-02 13:28 UTC, closed without merging