[WIP] Delay home queries to be non-blocking for the UI
saleor/saleor-dashboard pull request #4405
Opened 2023-11-06 12:50 UTC by poulch

closes https://github.com/saleor/saleor-dashboard/issues/4392

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `data-test-id` are added for new elements
4. [ ] The changes are tested in Chrome/Firefox/Safari browsers and in light/dark mode
5. [ ] Your code works with the latest stable version of the core
6. [ ] I added changesets file (instructions in [contribution guide](https://github.com/saleor/saleor-dashboard/blob/main/.github/CONTRIBUTING.md)

### Test environment config

API_URI=https://automation-dashboard.staging.saleor.cloud/graphql/
APPS_MARKETPLACE_API_URI=https://apps.staging.saleor.io/api/v2/saleor-apps

### Do you want to run more stable tests?

To run all tests, just select the stable checkbox. To speed up tests, increase the number of containers. Tests will be re-run only when the "run e2e" label is added.

1. [ ] stable
2. [ ] app
3. [ ] attribute
4. [ ] category
5. [ ] collection
6. [ ] customer
7. [ ] giftCard
8. [ ] homePage
9. [ ] login
10. [ ] menuNavigation
11. [ ] navigation
12. [ ] orders
13. [ ] pages
14. [ ] payments
15. [ ] permissions
16. [ ] plugins
17. [ ] productType
18. [ ] products
19. [ ] sales
20. [ ] shipping
21. [ ] translations
22. [ ] variants
23. [ ] vouchers

CONTAINERS=2

2023-11-07 10:45 UTC, Droniu submitted a review, later dismissed
lgtm

2023-11-08 09:41 UTC, andrzejewsky requested changes

2023-11-08 09:41 UTC, andrzejewsky commented on src/home/views/index.tsx
> +    skip: noChannel || !hasPermissionToManageOrders,
could you co-locate it in the the components that they are related to? Having all calls within some parent component causes multiple renders whenever any of calls trigger some state update

2023-11-08 13:18 UTC, andrzejewsky submitted a review, later dismissed

2023-11-10 08:49 UTC, wojteknowacki approved these changes

2023-11-10 08:51 UTC, Droniu approved these changes

2023-11-10 08:51 UTC, merged