[TEST] [E2E] Delete shipping method from the shipping zone details page
saleor/saleor-dashboard pull request #4611
Opened 2024-01-09 07:20 UTC by yellowee

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

It covers [TC SALEOR_34](https://saleor.testmo.net/repositories/1?group_id=1193&case_id=7558)

2024-01-09 09:11 UTC, wojteknowacki commented on playwright/pages/dialogs/deleteShippingMethodDialog.ts
> +  }
```suggestion
  readonly page: Page;

  constructor(page: Page, readonly deleteButton = page.getByTestId("submit")) {
    this.page = page;
  }
```

2024-01-09 14:41 UTC, michalina-graczyk requested changes

2024-01-09 14:41 UTC, michalina-graczyk commented on playwright/tests/shippingMethods.spec.ts
>  test("TC: SALEOR_32 Add price rate to shipping method - with excluded zip codes adn excluded product @shipping-method @e2e", async ({
adn -> and

2024-01-09 14:41 UTC, michalina-graczyk commented on playwright/pages/shippingMethodsPage.ts
>        timeout: 10000,
is it necessary?

2024-01-09 14:41 UTC, michalina-graczyk commented on playwright/tests/shippingMethods.spec.ts
>  test("TC: SALEOR_33 Add weight rate to shipping method - with included zip codes adn excluded product @shipping-method @e2e", async ({
adn -> and

2024-01-10 09:40 UTC, yellowee commented on playwright/tests/shippingMethods.spec.ts
>  test("TC: SALEOR_32 Add price rate to shipping method - with excluded zip codes adn excluded product @shipping-method @e2e", async ({
fixed

2024-01-10 09:40 UTC, yellowee commented on playwright/tests/shippingMethods.spec.ts
>  test("TC: SALEOR_33 Add weight rate to shipping method - with included zip codes adn excluded product @shipping-method @e2e", async ({
fixed

2024-01-10 15:11 UTC, wojteknowacki commented on playwright/pages/dialogs/deleteShippingMethodDialog.ts
> +  }
```suggestion
  readonly deleteButton: Locator;

  constructor(page: Page, readonly deleteButton = page.getByTestId("submit")) {
    this.page = page;
  }
```

2024-01-10 15:19 UTC, wojteknowacki commented on playwright/tests/shippingMethods.spec.ts
> +  await expect(shippingMethodsPage.priceBasedRatesSection).toContainText(priceBasedRate);
Do you need it?

2024-01-11 08:18 UTC, andrzejewsky submitted a review, later dismissed
Seems like your test is not working + please fix the CI checks, eg. ts check

2024-01-11 09:01 UTC, wojteknowacki approved these changes

2024-01-12 08:39 UTC, andrzejewsky approved these changes

2024-01-12 08:40 UTC, merged