[E2E] Tests for page types
saleor/saleor-dashboard pull request #4765
Opened 2024-04-02 05:42 UTC by szczecha

As an admin user I can create page type [SALEOR_187](https://saleor.testmo.net/repositories/1?group_id=1178&case_id=18419)
As an admin user I can update page type [SALEOR_188](https://saleor.testmo.net/repositories/1?group_id=1178&case_id=18420)
As an admin user I can delete page type with assigned content [SALEOR_189](https://saleor.testmo.net/repositories/1?group_id=1178&case_id=18421)
As an admin user I can delete several page types [SALEOR_190](https://saleor.testmo.net/repositories/1?group_id=1178&case_id=18422)

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-04-02 07:31 UTC, poulch submitted a review, later dismissed

2024-04-02 07:31 UTC, poulch commented on playwright/tests/pageTypes.spec.ts
> +    const pageTypePage = new PageTypesPage(page);
```suggestion
    const pageTypePage = new PageTypesPage(page);
    
```

2024-04-02 09:05 UTC, yellowee requested changes

2024-04-02 09:05 UTC, yellowee commented on playwright/pages/pageTypesPage.ts
> +    readonly nameInput = page.locator("[name='name']"),
Suggestion: You can easily add here a data-test-id

2024-04-02 09:05 UTC, yellowee commented on playwright/tests/pageTypes.spec.ts
> +    await pageTypePage.expectSuccessBanner();
Add assertions please - currently you do not check if the page with correct details has been created

2024-04-03 09:34 UTC, poulch approved these changes

2024-04-03 12:39 UTC, yellowee approved these changes

2024-04-03 13:22 UTC, merged