Always show charge and authorised amount in payment section of order details
saleor/saleor-dashboard pull request #4821
Opened 2024-04-24 10:00 UTC by poulch

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-04-24 11:10 UTC, Droniu submitted a review, later dismissed

2024-04-26 07:52 UTC, Droniu submitted a review, later dismissed

2024-04-26 11:49 UTC, andrzejewsky requested changes
If the payment section now will show all payments summary, aggregated from all transactions in given order, we should inform the user about that:
- We can call section "Payments summery" instead of "Payment"
- We can add small text right below the title that explains what it presents eg. "A summary of all payments from registered transactions"

What do you think?

2024-04-26 12:20 UTC, Droniu approved these changes

2024-04-29 09:50 UTC, witoszekdev approved these changes

2024-05-15 09:38 UTC, andrzejewsky approved these changes

2024-05-16 14:09 UTC, merged