Prevent selecting products that are not avialable in selected channels
saleor/saleor-dashboard pull request #4826
Opened 2024-04-24 18:32 UTC by poulch

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-04-26 07:50 UTC, andrzejewsky approved these changes

2024-04-26 09:22 UTC, Droniu submitted a review, later dismissed

2024-04-29 11:37 UTC, yellowee requested changes
Failed testing: Please refer to https://linear.app/saleor/issue/MERX-383/assign-products-modal-not-updated-on-shipping-price-page

2024-05-16 10:42 UTC, Droniu approved these changes

2024-05-16 13:35 UTC, yellowee approved these changes

2024-05-17 07:46 UTC, merged