Add time to publication date and remove deprecated date fields
saleor/saleor-dashboard pull request #4856
Opened 2024-05-10 08:59 UTC by Cloud11PL

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-05-10 17:45 UTC, mirekm commented
Do we still need to fill the old date fields (`availableForPurchase` and `publicationDate`) with the selected date?

2024-05-13 07:37 UTC, Droniu approved these changes

2024-05-13 07:50 UTC, Cloud11PL commented
@mirekm No, Saleor syncs old fields with new fields 🙂

2024-05-13 16:55 UTC, andrzejewsky approved these changes

2024-05-14 07:42 UTC, Droniu submitted a review, later dismissed

2024-05-15 10:53 UTC, Droniu submitted a review, later dismissed

2024-05-15 10:53 UTC, Droniu commented on src/components/DateTimeTimezoneField.test.tsx
tests should follow AAA format

2024-05-15 10:53 UTC, Droniu commented on src/components/VisibilityCard/VisibilityCard.tsx
> +              {isPublished && publishedAt && Date.parse(publishedAt) < dateNow && (
this condition is a little difficult to read, i'd extract it but it's a nitpick really - up to you

2024-05-15 10:53 UTC, Droniu commented on src/components/VisibilityCard/VisibilityCard.tsx
> +                    Date.parse(availableForPurchaseAt) < dateNow && (
same here

2024-05-15 13:43 UTC, andrzejewsky submitted a review, later dismissed

2024-05-16 10:41 UTC, Droniu approved these changes

2024-05-17 08:35 UTC, andrzejewsky requested changes
When I click on the date it supposed to close the datepicker

2024-05-17 08:56 UTC, merged