Properly handle PRs to branches other than main
saleor/saleor-dashboard pull request #4951
Opened 2024-06-12 10:58 UTC by stmpn

This adjustment is needed to properly handle the cases where changes are being merged to branches other than main - in this case we need to use backup specific to the destination branch, instead of using the "main" backup.

2024-06-12 11:00 UTC, NyanKiyoshi approved these changes

2024-06-12 11:02 UTC, andrzejewsky approved these changes

2024-06-12 13:21 UTC, NyanKiyoshi approved these changes

2024-06-12 13:34 UTC, yellowee submitted a review, later dismissed

2024-06-12 13:42 UTC, yellowee approved these changes

2024-06-17 09:09 UTC, stmpn commented
This is ready for review and merge - @yellowee tested it, and it works both for main branch and for version branches.

cc @saleor/ui-guild, @NyanKiyoshi, @andrzejewsky

2024-06-17 09:11 UTC, NyanKiyoshi approved these changes

2024-06-17 09:12 UTC, yellowee approved these changes

2024-06-19 09:07 UTC, Droniu approved these changes

2024-06-19 12:55 UTC, andrzejewsky requested changes

2024-06-19 12:55 UTC, andrzejewsky commented on .changeset/early-ghosts-search.md
> +Properly handle PRs to branches other than main
_Now you can execute e2e tests on release branches_

2024-06-19 12:59 UTC, Droniu approved these changes

2024-06-19 13:09 UTC, andrzejewsky approved these changes

2024-06-20 07:49 UTC, poulch approved these changes

2024-06-26 07:23 UTC, merged