Align add discount with rest links
saleor/saleor-dashboard pull request #4958
Opened 2024-06-13 08:12 UTC by poulch

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

Before:
![Screenshot 2024-06-13 at 10 12 23](https://github.com/saleor/saleor-dashboard/assets/16362049/b90dd85d-ddb1-418c-9ce7-2c3f96464706)

After:
![Screenshot 2024-06-13 at 10 09 32](https://github.com/saleor/saleor-dashboard/assets/16362049/11bbbd8a-56eb-4a0c-8352-05670feb3ff8)

2024-06-13 08:58 UTC, Cloud11PL requested changes

2024-06-13 08:58 UTC, Cloud11PL commented on src/orders/components/OrderDraftDetailsSummary/OrderDraftDetailsSummary.tsx
> +                <Box onClick={isDialogOpen ? closeDialog : openDialog}>
Issue: This is not accessible and you can't select it with a keyboard. 

I would propose a Link variant to the Button, something like this:
```
                <Button
                  variant="tertiary"
                  onClick={isDialogOpen ? closeDialog : openDialog}
                  __backgroundColor="transparent"
                  textDecoration={{
                    hover: "underline",
                    focus: "underline",
                  }}
                  style={{
                    textUnderlineOffset: "4px",
                    padding: 0,
                    margin: 0,
                    height: "1rem",
                    textDecorationColor: vars.colors.border.accent1,
                  }}
                >
                  <Link>{intl.formatMessage(discountTitle)}</Link>
                </Button>
                ```

2024-06-14 13:36 UTC, Cloud11PL submitted a review, later dismissed
LGTM, but I think changesets got doubled

2024-06-17 09:56 UTC, andrzejewsky approved these changes

2024-06-17 11:26 UTC, Cloud11PL approved these changes

2024-06-17 11:41 UTC, merged