Fix group permission issue for oauth users
saleor/saleor-dashboard pull request #4963
Opened 2024-06-14 08:11 UTC by Cloud11PL

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-06-14 10:31 UTC, poulch submitted a review, later dismissed

2024-06-17 10:24 UTC, Droniu submitted a review, later dismissed

2024-06-17 10:58 UTC, andrzejewsky requested changes

2024-06-17 10:58 UTC, andrzejewsky commented on .changeset/lucky-cameras-taste.md
> +Fixes an issue where OAuth user were unable to edit permission groups even though they had full access
_You can now properly edit permission groups when you have full access_

2024-06-17 11:35 UTC, poulch approved these changes

2024-06-18 07:31 UTC, andrzejewsky approved these changes

2024-06-18 07:49 UTC, merged