Adjust shipping warning in draft order creation
saleor/saleor-dashboard pull request #4967
Opened 2024-06-14 12:49 UTC by Cloud11PL

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

![image](https://github.com/saleor/saleor-dashboard/assets/13994677/99a96a5a-4c88-452d-b4a3-d81d432a81ea)

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-06-17 11:04 UTC, andrzejewsky requested changes

2024-06-17 11:04 UTC, andrzejewsky commented on .changeset/six-hairs-cover.md
> +Now 'no shipping method' warning in draft order creation has an improved, clearer message
_Now you can see the reason why shipping methods are incorrect when creating draft orders. This means creating new draft orders will pop up an error with the details of incorrect shipping._

2024-06-17 11:43 UTC, poulch approved these changes

2024-06-18 07:32 UTC, andrzejewsky approved these changes

2024-06-18 07:43 UTC, merged