Implement new savebar
saleor/saleor-dashboard pull request #4975
Opened 2024-06-19 22:43 UTC by poulch

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-06-21 07:28 UTC, Cloud11PL approved these changes

2024-06-21 09:25 UTC, Cloud11PL approved these changes

2024-06-24 07:38 UTC, andrzejewsky requested changes

2024-06-24 07:38 UTC, andrzejewsky commented on .changeset/dry-geckos-laugh.md
> +Prepare new savebar component
Now, the developer can access sidebar components on each page directly.

2024-06-24 07:45 UTC, Droniu approved these changes

2024-06-24 07:50 UTC, andrzejewsky approved these changes

2024-06-24 08:17 UTC, merged