Fix scroll in MenuItem in navigation section
saleor/saleor-dashboard pull request #5023
Opened 2024-07-03 21:18 UTC by soniaklimas

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [X ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ X] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-07-03 21:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/saleor/saleor-dashboard?pullRequest=5023) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/saleor/saleor-dashboard?pullRequest=5023) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/saleor/saleor-dashboard?pullRequest=5023) it.</sub>

2024-07-04 08:56 UTC, poulch requested changes
Your solution solved the problem, but replacing this component with Combobox has already solved this issue.
I'm not happy with testing scroll in test, I'd skip testing this.

2024-08-09 08:13 UTC, poulch approved these changes

2024-08-09 08:18 UTC, andrzejewsky approved these changes

2024-08-09 08:19 UTC, merged