Add saleor-dev-data-test service to dev deployment workflow
saleor/saleor-dashboard pull request #5054
Opened 2024-07-18 17:50 UTC by cmiacz

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-07-18 17:55 UTC, szczecha submitted a review, later dismissed

2024-07-18 19:42 UTC, poulch approved these changes

2024-07-18 19:44 UTC, poulch requested changes
@cmiacz could you run `npm run change:add` select patch if changes can be release in upcoming patch otherwise minor, and provide description of changes

2024-07-19 08:24 UTC, poulch approved these changes

2024-07-19 08:26 UTC, NyanKiyoshi approved these changes

2024-07-19 08:38 UTC, szczecha approved these changes

2024-07-19 08:40 UTC, merged