Improve Stability of Authentication Setup Tests
saleor/saleor-dashboard pull request #5121
Opened 2024-08-20 19:56 UTC by michalina-graczyk

## What type of PR is this?
- [x] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [x] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

This PR addresses issues with flaky Playwright authentication tests, especially related to undefined cookie values.

#### Key Changes

1. **Safe Property Access**
   - Added optional chaining to prevent crashes when cookies are missing.

2. **Retry Mechanism**
   - Implemented retries (up to 3 times) for the authentication process to handle intermittent failures.

3. **Improved Logging**
   - Enhanced logging for better insight into failures, especially when cookies are missing or API errors occur.

2024-08-20 20:41 UTC, michalina-graczyk commented
After applying the changes the test provided the following output:

```
Login error (code: LOGIN_ATTEMPT_DELAYED): Logging has been suspended till 2024-08-20 20:04:37.030798+00:00 due to too many logging attempts originating from the same IP address.
Authentication failed, retrying 1/3...
Login error (code: LOGIN_ATTEMPT_DELAYED): Logging has been suspended till 2024-08-20 20:04:37.929046+00:00 due to too many logging attempts originating from the same IP address.
Authentication failed, retrying 2/3...
Login error (code: LOGIN_ATTEMPT_DELAYED): Logging has been suspended till 2024-08-20 20:04:38.807281+00:00 due to too many logging attempts originating from the same IP address.
Authentication failed, retrying 3/3...
```

Can we whitelist the servers from which these auth attempts are performed during the CI phase?

2024-08-21 07:48 UTC, andrzejewsky requested changes

2024-08-21 07:48 UTC, andrzejewsky commented on playwright/tests/auth.setup.ts
> +  while (retries < maxRetries) {
we can't login in a loop until API will pass - I don't think that fixes anything:

PW have nice guides how to do login stuff, in our case we need to login and share sessions across the workers: https://playwright.dev/docs/auth#moderate-one-account-per-parallel-worker

2024-08-21 07:48 UTC, andrzejewsky commented on playwright/tests/auth.setup.ts
> +  while (retries < maxRetries) {
We should login accordingly to the API limits, not fighting with them. When we reach limitations that means either doing something wrong or API has a bug

2024-08-21 09:03 UTC, closed without merging