Clicking "Select channel" does not cause URL change
saleor/saleor-dashboard pull request #5164
Opened 2024-09-16 19:00 UTC by poulch

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-09-17 07:34 UTC, Cloud11PL commented on .changeset/gentle-seahorses-tease.md
> +You can now see now changes in URL when click "Select channel" in product list
Suggestion: I would change the changeset a bit

Maybe `"Select channel" button in product list no longer changes the URL` ?

2024-09-17 08:32 UTC, Cloud11PL submitted a review, later dismissed

2024-09-19 08:10 UTC, andrzejewsky requested changes
Test please

2024-09-19 13:43 UTC, andrzejewsky approved these changes

2024-09-20 07:52 UTC, Cloud11PL approved these changes

2024-09-20 07:52 UTC, merged