Bump 'breakword' package version
saleor/saleor-dashboard pull request #5202
Opened 2024-10-07 10:59 UTC by Cloud11PL

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-10-07 11:15 UTC, poulch submitted a review, later dismissed

2024-10-10 10:05 UTC, andrzejewsky requested changes

2024-10-10 10:05 UTC, andrzejewsky commented on package.json
> +    "breakword": "^1.0.6"
probably you need to update changeset-cli itself as this library is using that directly, instead of overriding

2024-10-10 11:21 UTC, poulch approved these changes

2024-10-10 14:16 UTC, poulch approved these changes

2024-10-14 09:45 UTC, andrzejewsky approved these changes

2024-10-15 06:46 UTC, merged