Fix for TC: SALEOR_38
saleor/saleor-dashboard pull request #5207
Opened 2024-10-10 13:52 UTC by karola312

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-10-10 14:24 UTC, poulch submitted a review, later dismissed

2024-10-11 07:31 UTC, szczecha submitted a review, later dismissed

2024-10-11 11:16 UTC, andrzejewsky requested changes

2024-10-11 11:16 UTC, andrzejewsky commented on .changeset/eleven-avocados-draw.md
> +Test for activation staff member TC:38 should always work
this is a bit broken, mention why it didn't work, what exactly have you fixed here. For now it's exactly same test copy-pasted to the separated file

2024-10-11 12:55 UTC, michalina-graczyk approved these changes

2024-10-14 09:01 UTC, michalina-graczyk approved these changes

2024-10-17 07:03 UTC, szczecha approved these changes

2024-10-17 07:57 UTC, poulch submitted a review, later dismissed

2024-11-06 11:57 UTC, michalina-graczyk approved these changes

2024-11-06 12:48 UTC, szczecha approved these changes

2024-11-06 13:55 UTC, andrzejewsky approved these changes

2024-11-06 13:55 UTC, merged