Fix: truncate attribute plainText
saleor/saleor-dashboard pull request #5225
Opened 2024-10-22 11:42 UTC by peelar

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [X] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Usage Instructions, Screenshots, Recordings

![image](https://github.com/user-attachments/assets/a65903d4-34b6-4818-a04a-f6c39b52253d)

## Have you written tests?
- [X] Yes!

## [Optional] Description
Dashboard crashes when the value of the attribute `plainText` is too long. This PR fixes it by truncating the content to 255 characters and displaying a helper text.

2024-10-23 12:50 UTC, witoszekdev requested changes

2024-10-23 12:50 UTC, witoszekdev commented on src/attributes/components/AttributeDetails/messages.tsx
Please run `npm run extract-message` for CI to pass

2024-10-23 14:17 UTC, poulch approved these changes

2024-10-25 10:49 UTC, peelar commented
@witoszekdev 🙏

2024-10-25 10:50 UTC, witoszekdev approved these changes

2024-10-28 12:02 UTC, andrzejewsky approved these changes

2024-10-28 13:16 UTC, poulch approved these changes

2024-10-28 13:17 UTC, merged