Home onboarding logic
saleor/saleor-dashboard pull request #5274
Opened 2024-11-21 21:09 UTC by poulch

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-11-25 11:55 UTC, NyanKiyoshi submitted a review, later dismissed

2024-11-25 11:55 UTC, NyanKiyoshi commented on .github/workflows/deploy-cloud.yaml
> +      ONBOARDING_USER_JOINED_DATE_THRESHOLD: ${{ secrets.ONBOARDING_USER_JOINED_DATE_THRESHOLD }}
Is it intentional the date is stored as a secret? Didn't you mean to use environment variables instead? (https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#creating-configuration-variables-for-a-repository)

2024-11-26 10:48 UTC, Cloud11PL requested changes

2024-11-26 10:48 UTC, Cloud11PL commented on src/newHome/homeOnboarding/useOnboardingData.tsx
> +    isStepCompleted: (step: OnboardingStepsIDs) => onboardingState.stepsCompleted.includes(step),
Issue: This hooks is duplicated

2024-11-26 11:40 UTC, Cloud11PL approved these changes

2024-11-26 12:00 UTC, andrzejewsky approved these changes

2024-11-26 12:07 UTC, merged