Merx 198 improvement
saleor/saleor-dashboard pull request #5296
Opened 2024-12-02 10:53 UTC by michalina-graczyk

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-12-02 13:59 UTC, szczecha submitted a review, later dismissed

2024-12-03 15:03 UTC, poulch submitted a review, later dismissed

2024-12-19 09:02 UTC, szczecha approved these changes

2024-12-27 12:28 UTC, andrzejewsky requested changes

2024-12-27 12:28 UTC, andrzejewsky commented on playwright/pages/dialogs/addNavigationMenuItemDialog.ts
> +      throw new Error(`Expected link type "${linkType}" but found "${selectedLinkType}"`);
this should be an assert, not exception raising, this will break the test execution by unhandled error

2024-12-27 12:28 UTC, andrzejewsky commented on playwright/pages/dialogs/addNavigationMenuItemDialog.ts
> +    // Ensure the link type option is visible and select it
LLM models generate usually tons on comments, explaining what they do - it's useful when composing the final solution, but usually redundant when used in the final codebase.

2025-01-13 02:03 UTC, closed without merging