Split select options into 2
saleor/saleor-dashboard pull request #5301
Opened 2024-12-04 14:19 UTC by michalina-graczyk

## What type of PR is this?
- [ ] 💅 Refactor
- [ ] 🌟 Feature
- [ ] 🔥 Bug Fix
- [ ] 🔩 Maintenance
- [ ] 🛠 Workflow CI/CD changes

## Related Issues or Documents

- closes #

## Usage Instructions, Screenshots, Recordings

## Have you written tests?
- [ ] Yes!
- [ ] No... here is why: _Writing tests are mandatory, please replace this text with why test are not included in this PR_

## [Optional] Description

2024-12-18 12:53 UTC, witoszekdev requested changes

2024-12-18 12:53 UTC, witoszekdev commented on .changeset/stupid-peas-work.md
> +Split select link option to 2 differen one to avoid flakyness
suggestion: typo

```suggestion
Split select link option into 2 different ones to avoid flakyness in tests
```

2024-12-23 09:05 UTC, szczecha approved these changes

2024-12-23 13:03 UTC, szczecha approved these changes

2024-12-24 11:43 UTC, witoszekdev approved these changes

2024-12-27 10:31 UTC, merged